<?php
declare(strict_types=1);
/**
 * WBCE CMS
 * Way Better Content Editing.
 * Visit https://wbce.org to learn more and to join the community.
 *
 * @copyright Ryan Djurovich (2004-2009)
 * @copyright WebsiteBaker Org. e.V. (2009-2015)
 * @copyright WBCE Project (2015-)
 * @license GNU GPL2 (or any later version)
 */

defined('WB_PATH') or die("Access Denied");

class Wbce extends SecureForm
{
    // DirectOutput: private state replaces the old public $sDirectOutput property.
    // __set() below intercepts any legacy $wb->sDirectOutput = '...' assignments.
    private string  $directOutput      = '';
    private bool    $directPending     = false;
    private ?string $directContentType = null;

    public $page_sections = array();
    /**
     * Allowed characters for password validation (used as regex character class).
     * \x20-\x7E = all 95 printable ASCII characters:
     *   !"#$%&'()*+,-./0-9:;<=>?@A-Z[\]^_`a-z{|}~
     * Covers all characters generated by wbePwGen.
     */
    public $password_chars = '\x20-\x7E';
    public $iPassMinLength = 12;

    public function __construct(int $mode = SecureForm::FRONTEND)
    {
        parent::__construct($mode);
    }

    /**
     * Check if the Password matches the required pattern and length,
     * and encode it correctly if valid. Returns an error message array on failure.
     *
     * @param string      $sPassword
     * @param string|null $sNewPasswordRetyped
     * @return array|string  Array of error messages, or encoded password string on success.
     * @global array $MESSAGE
     */
    public function checkPasswordPattern(string $sPassword, ?string $sNewPasswordRetyped = null): array|string
    {
        global $MESSAGE;
        $iMinPassLength = 6;
        $bPasswordOk = false;
        $aErrMsg = array();
        if ($sPassword != '') {
            $sPattern = '/[^' . $this->password_chars . ']/';
            if (preg_match($sPattern, $sPassword)) {
                $aErrMsg[] = $MESSAGE['PREFERENCES_INVALID_CHARS'] . '[1]';
            } else {
                $bPasswordOk = true;
            }
            if ($sNewPasswordRetyped != null) {
                if ($sPassword != $sNewPasswordRetyped) {
                    $aErrMsg[] = $MESSAGE['USERS_PASSWORD_MISMATCH'] . '[2]';
                }
            }
            if (strlen($sPassword) < $iMinPassLength) {
                $aErrMsg[] = $MESSAGE['USERS_PASSWORD_TOO_SHORT'] . '[3]';
            }
        }

        return (!empty($aErrMsg)) ? $aErrMsg : $this->doPasswordEncode($sPassword);
    }

    /**
     * Hash a password using PHP's password_hash (PASSWORD_DEFAULT).
     *
     * @param  string $sPassword
     * @return string
     */
    public function doPasswordEncode(string $sPassword): string
    {
        if (function_exists('password_hash')) {
            return password_hash($sPassword, PASSWORD_DEFAULT);
        }
        return md5($sPassword); // fallback — should never be reached on PHP 8
    }

    /**
     * Checks if the supplied password is correct for the given user.
     * If it is an old md5 hash, it will be automatically upgraded to a modern hash.
     *
     * @param int    $userId
     * @param string $password
     * @return bool
     */
    public function doCheckPassword(int $userId, string $password): bool
    {
        $sql = 'SELECT `password` FROM `{TP}users`
                WHERE `user_id` = ? AND `active` = 1';

        $dbPasswordHash = $this->db->fetchValue($sql, [$userId]);

        if ($dbPasswordHash === '') {   // fetchValue returns '' on no result / error
            return false;
        }

        // Check if it's still an old md5 hash
        if (strpos($dbPasswordHash, '$') === false) {
            // Old md5 hash → verify with md5
            if ($dbPasswordHash === md5($password)) {
                // Password correct → upgrade to modern hash
                $newHash = $this->doPasswordEncode($password);

                $updateSql = 'UPDATE `{TP}users`
                              SET `password` = ?
                              WHERE `user_id` = ? AND `active` = 1';

                $this->db->query($updateSql, [$newHash, $userId]);

                return true;
            }

            return false; // wrong password (old md5)
        }

        // Modern password hash
        return password_verify($password, $dbPasswordHash);
    }

    /**
     * Returns a password input with the wbePwGen strength meter and generator.
     *
     * Enqueues wbePwGen CSS/JS (idempotent via I:: key) and emits an inline
     * WbePwGen.attach() call so the widget initialises in both full-page and
     * HTMX-fragment contexts.
     *
     * @param string $sNameAttr  The input name/id attribute.
     * @param string $confirmId  ID of the confirm field. Auto-derived when empty:
     *                           foo_1 → foo_2, foo → foo2.
     * @param int    $maxWidth   Explicit row max-width in px. 0 = auto-detect from theme
     *                           CSS (works when theme uses max-width on inputs, e.g. 300px).
     *                           Pass the value explicitly for themes that use width instead
     *                           of max-width (e.g. flat_theme uses .wdt250 = 250px).
     */
    public function passwordField(string $sNameAttr = '', string $confirmId = '', int $maxWidth = 0, string $value = ''): string
    {
        if ($sNameAttr === '') {
            return '';
        }

        if ($confirmId === '') {
            $confirmId = preg_match('/_1$/', $sNameAttr)
                ? preg_replace('/_1$/', '_2', $sNameAttr)
                : $sNameAttr . '2';
        }

        // Enqueue assets — idempotent via key
        $base = WB_URL . '/include/wbePwGen/';
        I::insertCssFile($base . 'wbePwGen.css', 'HEAD BTM-', 'wbePwGen');
        I::insertJsFile($base . 'wbePwGen.js',  'HEAD BTM-', 'wbePwGen');

        // Load localised labels into local scope (plain include so it re-runs here)
        include WB_PATH . '/include/wbePwGen/i18n.php';

        $extra = ['minLength' => $this->iPassMinLength, 'confirmId' => $confirmId];
        if ($maxWidth > 0) $extra['maxWidth'] = $maxWidth;

        $opts = json_encode(array_merge($wpg_labels, $extra));

        // Inline <script> covers both full-page render and HTMX-fragment swap
        return '<input type="password"'
             . ' id="'        . $sNameAttr . '"'
             . ' name="'      . $sNameAttr . '"'
             . ' minlength="' . $this->iPassMinLength . '"'
             . ' value="' . htmlspecialchars($value, ENT_QUOTES, 'UTF-8') . '" autocomplete="new-password" />' . "\n"
             . '<div id="' . $sNameAttr . '-wrap" class="wpg-wrap"></div>' . "\n"
             . '<script>WbePwGen.attach('
             .     json_encode($sNameAttr) . ','
             .     json_encode($sNameAttr . '-wrap') . ','
             .     $opts
             . ');</script>';
    }

    /**
     * Queue content for direct output, bypassing normal page rendering.
     *
     * The full index.php pipeline (modules, template, OutputFilter) runs
     * to completion first. At the very end, sendDirectOutput() flushes all
     * output buffers, sends this content, and exits.
     *
     * Calls are additive: multiple setDirectOutput() calls append content.
     *
     * @param string      $content      The response body to send
     * @param string|null $contentType  Optional Content-Type header value
     */
    public function setDirectOutput(string $content, ?string $contentType = null): void
    {
        $this->directOutput  .= $content;
        $this->directPending  = true;
        if ($contentType !== null) {
            $this->directContentType = $contentType;
        }
    }

    /** Returns true if direct output has been queued. */
    public function hasDirectOutput(): bool
    {
        return $this->directPending;
    }

    /**
     * Send queued direct output and exit. No-op if nothing was queued.
     * Called once at the end of index.php
     * and once in class Admin::print_footer() in place of the old DirectOutput().
     */
    public function sendDirectOutput(): void
    {
        if (!$this->directPending) return;

        if ($this->directContentType !== null) {
            header('Content-Type: ' . $this->directContentType);
        }

        while (ob_get_level()) ob_end_clean();

        echo $this->directOutput;
        exit;
    }

    /**
     * @deprecated Use setDirectOutput() to queue content, sendDirectOutput() to send.
     *             Kept for backward compatibility with older modules.
     */
    public function DirectOutput(string|false $content = false): void
    {
        if (is_string($content)) {
            $this->setDirectOutput($content);
        } else {
            $this->sendDirectOutput();
        }
    }

    /**
     * Intercept legacy $wb->sDirectOutput = '...' assignments.
     * Redirects them to setDirectOutput() so old modules keep working.
     */
    public function __set(string $name, mixed $value): void
    {
        if ($name === 'sDirectOutput' && is_string($value)) {
            $this->setDirectOutput($value);
            return;
        }
        $this->$name = $value;
    }

    /**
     * Check if the current user is a member of at least one of the given groups.
     * SuperAdmin (primary group 1) is always considered a member of all groups.
     *
     * @param  array|string $mGroups  Array or comma-separated list of group IDs
     * @return bool
     */
    public function isInGroup(array|string $mGroups = ''): bool
    {
        if ($this->get_group_id() == 1) {
            return true;
        }
        return $this->is_group_match($mGroups, $this->get_groups_id());
    }

    /**
     * @deprecated Use isInGroup() instead.
     *             Kept for backward compatibility with droplets and third-party modules.
     */
    public function ami_group_member(array|string $mGroups = ''): bool
    {
        return $this->isInGroup($mGroups);
    }

    /**
     * Check if the current user has admin rights for a page based on
     * the raw admin_groups / admin_users values from {TP}pages.
     *
     * Available in both backend (Admin) and frontend (Frontend) contexts,
     * e.g. for inline-edit or frontend-edit modules.
     *
     * Handles both the old _N_N_ underscore format and the modern N,N CSV.
     * The superadmin (primary group 1) always passes — same bypass as isInGroup().
     *
     * @param  string $adminGroups  admin_groups value from {TP}pages
     * @param  string $adminUsers   admin_users  value from {TP}pages
     * @return bool
     */
    public function isPageAdmin(string $adminGroups, string $adminUsers = ''): bool
    {
        if ($this->get_group_id() == 1) {
            return true;
        }
        $groups = explode(',', str_replace('_', '', $adminGroups));
        $users  = explode(',', str_replace('_', '', $adminUsers));
        return $this->is_group_match($groups, $this->get_groups_id())
            || in_array((string) $this->get_user_id(), $users, true);
    }

    /**
     * Get the current user's primary GROUP_ID.
     *
     * @return int|null
     */
    public function get_group_id(): mixed
    {
        return $this->get_session('GROUP_ID');
    }

    /**
     * Get a value from the session by key.
     *
     * @param  string $field
     * @return mixed
     */
    public function get_session(string $field): mixed
    {
        return $_SESSION[$field] ?? null;
    }

    /**
     * Check if one or more group IDs appear in both group lists.
     *
     * @param  array|string $mGroups_1  Array or CSV of group IDs
     * @param  array|string $mGroups_2  Array or CSV of group IDs
     * @param  array|null   &$matches   Receives the matched group IDs
     * @return bool
     */
    public function is_group_match(array|string $mGroups_1 = '', array|string $mGroups_2 = '', ?array &$matches = null): bool
    {
        if ($mGroups_1 == '' || $mGroups_2 == '') {
            return false;
        }
        if (!is_array($mGroups_1)) {
            $mGroups_1 = explode(',', $mGroups_1);
        }
        if (!is_array($mGroups_2)) {
            $mGroups_2 = explode(',', $mGroups_2);
        }
        $matches = array_intersect($mGroups_1, $mGroups_2);
        return (sizeof($matches) != 0);
    }

    /**
     * Get all group IDs the current user belongs to.
     *
     * @return array
     */
    public function get_groups_id() : array
    {
        $session_groups = $this->get_session('GROUPS_ID');
        $groups = (
            (!empty($session_groups))
            ? explode(",", $session_groups)
            : []
        );
        return $groups;
    }

    /**
     * Check whether a page should be shown in the frontend
     * (visible and has at least one active section).
     *
     * @param  array $page
     * @return bool
     */
    public function show_page(array $page): bool
    {
        return $this->page_is_visible($page) && $this->page_is_active($page);
    }

    /**
     * Check whether a page is visible to the current user.
     *
     * Returns false for visibility 'none' or 'deleted', and for 'private' /
     * 'registered' pages when the user is not authenticated or lacks permission.
     *
     * @param  array $page
     * @return bool
     */
    public function page_is_visible(array $page): bool
    {
        $show_it = false;
        $visibility     = $page['visibility'];
        $viewing_groups = $page['viewing_groups'];
        $viewing_users  = $page['viewing_users'];

        if ($visibility == 'none' || $visibility == 'deleted') {
            return false;
        }

        if ($visibility == 'hidden') {
            $show_it = true;
        } elseif ($visibility == 'private' || $visibility == 'registered') {
            if ($this->is_authenticated() == true) {
                $in_group = false;
                foreach ($this->get_groups_id() as $cur_gid) {
                    if (in_array($cur_gid, explode(',', $viewing_groups))) {
                        $in_group = true;
                    }
                }
                $show_it = $in_group || in_array($this->get_user_id(), explode(',', $viewing_users));
            }
        } elseif ($visibility == 'public') {
            $show_it = true;
        }

        return ($show_it);
    }

    /**
     * @deprecated Use isLoggedIn() instead.
     * @return bool
     */
    public function is_authenticated(): bool
    {
        return $this->isLoggedIn();
    }

    /**
     * Check if the user is logged in.
     *
     * @return bool
     */
    public function isLoggedIn(): bool
    {
        $iSessionUserID = $this->get_session('USER_ID');
        return ($iSessionUserID != null && $iSessionUserID != "" && is_numeric($iSessionUserID));
    }

    /**
     * Get the current user's USER_ID.
     *
     * @return mixed
     */
    public function get_user_id(): mixed
    {
        return $this->get_session('USER_ID');
    }

    /**
     * Update modified_when / modified_by on a page.
     * Use for page-level changes (settings, visibility, etc.).
     * For section content changes use touchSection() — it calls this automatically.
     *
     * @param  int  $page_id
     * @return bool
     */
    public function touchPage(int $page_id): bool
    {
        global $database;
        return (bool) $database->query(
            "UPDATE `{TP}pages` SET `modified_when` = ?, `modified_by` = ? WHERE `page_id` = ?",
            [time(), $this->get_user_id(), $page_id]
        );
    }

    /**
     * Update modified_when / modified_by on a section and its parent page.
     * page_id is resolved automatically — no need to pass it.
     * A section change always implies a page change, not the other way around.
     *
     * @param  int  $section_id
     * @return bool
     */
    public function touchSection(int $section_id): bool
    {
        global $database;
        $page_id = (int) $database->fetchValue(
            "SELECT `page_id` FROM `{TP}sections` WHERE `section_id` = ?",
            [$section_id]
        );
        $ok = (bool) $database->query(
            "UPDATE `{TP}sections` SET `modified_when` = ?, `modified_by` = ? WHERE `section_id` = ?",
            [time(), $this->get_user_id(), $section_id]
        );
        if ($page_id > 0) {
            $this->touchPage($page_id);
        }
        return $ok;
    }

    /**
     * Check if there is at least one active section on this page.
     *
     * @param  array $page
     * @return bool
     */
    public function page_is_active(array $page): bool
    {
        $has_active_sections = false;
        $now = time();
        $sql = "SELECT `publ_start`, `publ_end` FROM `{TP}sections` WHERE `page_id`= ?";
        $query_sections = $this->db->query($sql, [$page['page_id']]);
        if ($query_sections->numRows() != 0) {
            while ($section = $query_sections->fetchRow()) {
                if ($now < $section['publ_end'] && ($now > $section['publ_start'] || (int)$section['publ_start'] == 0) || $now > $section['publ_start'] && (int)$section['publ_end'] == 0) {
                    $has_active_sections = true;
                    break;
                }
            }
        }
        return ($has_active_sections);
    }

    /**
     * Check if the current user is the SuperAdmin (user_id = 1).
     *
     * @return bool
     */
    public function isSuperAdmin(): bool
    {
        return ($this->get_session('USER_ID') == 1);
    }

    /**
     * Check if the current user is an Administrator (group_id = 1).
     *
     * @return bool
     */
    public function isAdmin(): bool
    {
        if ($this->get_session('GROUP_ID') == 1) {
            return true;
        }
        return (in_array(1, $this->get_groups_id()));
    }

    /**
     * @deprecated No-op — kept for backward compatibility with modules that relied on magic_quotes.
     *
     * @param  string $input
     * @return string  unchanged
     */
    public function strip_magic(mixed $input): mixed
    {
        return $input;
    }

    /**
     * Escape backslashes for use in MySQL LIKE strings.
     *
     * @param  string $input
     * @return string
     */
    public function escape_backslashes(string $input): string
    {
        return str_replace("\\", "\\\\", $input);
    }

    /**
     * Generate a full page URL from a page ID or link string stored in {TP}pages.
     *
     * @param  int|string|null $linkId  Page ID or link string
     * @return string                   Full URL to the page
     */
    public function page_link($linkId = null): string
    {
        if ($linkId === null) {
            if (defined('PAGE_ID')) {
                $linkId = (int) PAGE_ID;
            } elseif (isset($_GET['page_id']) && is_numeric($_GET['page_id'])) {
                $linkId = (int) $_GET['page_id'];
            }
        }

        if (is_numeric($linkId)) {
            $sql = 'SELECT `link` FROM `{TP}pages` WHERE `page_id` = ?';
            $pageLink = $this->db->fetchValue($sql, [(int)$linkId]);

            if ($pageLink === '') {
                return ''; // page not found
            }

            return WB_URL . PAGES_DIRECTORY . $pageLink . PAGE_EXTENSION;
        }

        $linkId = (string)$linkId;

        if (str_contains($linkId, '://') || str_starts_with($linkId, 'mailto:')) {
            return $linkId;
        }

        return WB_URL . PAGES_DIRECTORY . $linkId . PAGE_EXTENSION;
    }

    /**
     * Get a POST value (HTML-escaped).
     *
     * @param  string $field
     * @return string|null
     */
    public function get_post_escaped(string $field): mixed
    {
        return $this->get_post($field);
    }

    /**
     * Get a POST value.
     *
     * @param  string $field
     * @return mixed
     */
    public function get_post(string $field): mixed
    {
        return $_POST[$field] ?? null;
    }

    /**
     * Get a GET value.
     *
     * @param  string $field
     * @return mixed
     */
    public function get_get(string $field): mixed
    {
        return $_GET[$field] ?? null;
    }

    /**
     * Get a SERVER value.
     *
     * @param  string $field
     * @return mixed
     */
    public function get_server(string $field): mixed
    {
        return $_SERVER[$field] ?? null;
    }

    /**
     * Get the current user's group names as a CSV string.
     *
     * @return string
     */
    public function get_group_name(): string
    {
        return implode(",", (array) $this->get_session('GROUP_NAME'));
    }

    /**
     * Get the current user's group names as an array.
     *
     * @return array|null
     */
    public function get_groups_name(): ?array
    {
        return $this->get_session('GROUP_NAME');
    }

    /**
     * Get the current user's USERNAME.
     *
     * @return string|null
     */
    public function get_username(): ?string
    {
        return $this->get_session('USERNAME');
    }

    /**
     * Get the current user's DISPLAY_NAME (special characters stripped).
     *
     * @return string
     */
    public function get_display_name(): string
    {
        return remove_special_characters((string) $this->get_session('DISPLAY_NAME'));
    }

    /**
     * Get the current user's email address.
     *
     * @return string|null
     */
    public function get_email(): ?string
    {
        return $this->get_session('EMAIL');
    }

    /**
     * Get the current user's home folder.
     *
     * @return string|null
     */
    public function get_home_folder(): ?string
    {
        return $this->get_session('HOME_FOLDER');
    }

    /**
     * Validate an email address.
     *
     * Handles internationalized domain names (IDN) by converting the domain
     * part to its ASCII-compatible encoding (ACE/Punycode) before validation.
     * Requires the intl extension for IDN support (idn_to_ascii).
     * Falls back to raw domain validation if the extension is unavailable.
     *
     * @param  string $email
     * @return bool
     *
     * @see https://www.php.net/manual/en/function.idn-to-ascii.php
     * @see https://www.php.net/manual/en/function.filter-var.php
     */
    public function validate_email(string $email): bool
    {
       if (empty($email)) {
           return false;
       }

       if (str_contains($email, '@')) {
           [$local, $domain] = explode('@', $email, 2);

           if (function_exists('idn_to_ascii')) {
               $ascii = idn_to_ascii($domain, IDNA_DEFAULT, INTL_IDNA_VARIANT_UTS46);
               if ($ascii !== false) {
                   $domain = $ascii;
               }
           }

           $email = $local . '@' . $domain;
       }

       return filter_var($email, FILTER_VALIDATE_EMAIL) !== false;
    }

    /**
     * Set one or more bits in an integer value.
     *
     * @param int $value     Reference to the integer
     * @param int $bits2set  Bitmask to add
     */
    public function bit_set(int &$value, int $bits2set): void
    {
        $value |= $bits2set;
    }

    /**
     * Clear one or more bits from an integer value.
     *
     * @param int $value      Reference to the integer
     * @param int $bits2reset Bitmask to remove
     */
    public function bit_reset(int &$value, int $bits2reset): void
    {
        $value &= ~$bits2reset;
    }

    /**
     * Test whether one or more bits are set in an integer value.
     *
     * @param  int  $value
     * @param  int  $bits2test  Bitmask to test
     * @return bool
     */
    public function bit_isset(int $value, int $bits2test): bool
    {
        return (($value & $bits2test) == $bits2test);
    }

    /**
     * Print a success message that automatically redirects to a specified page.
     *
     * @param mixed  $uMsg          Single string or array of messages
     * @param string $sRedirectUri  Redirect target
     * @param bool   $bAutoFooter
     */
    public function print_success(array|string $uMsg, string $sRedirectUri = 'index.php', bool $bAutoFooter = false): void
    {
        $this->messageBox($uMsg, 'success', $sRedirectUri, $bAutoFooter);
    }

    /**
     * Print a modal message box (success, error, info, etc.).
     *
     * @param mixed  $uMsg          Single string or array of messages
     * @param string $sType         'success' | 'error' | 'info'
     * @param string $sRedirectUri  URL for redirect or back-button
     * @param bool   $bAutoFooter   Call print_footer() and exit automatically
     * @param bool   $bUseRedirect
     */
    public function messageBox(array|string $uMsg, string $sType = 'info', string $sRedirectUri = 'index.php', bool $bAutoFooter = false, bool $bUseRedirect = true): void
    {
        if (!is_array($uMsg)) {
            $uMsg = array($uMsg);
        }

        $iRedirectTime = (defined('REDIRECT_TIMER')) ? REDIRECT_TIMER : 0;
        $iRedirectTime = ($iRedirectTime > 10000) ? 10000 : $iRedirectTime;

        $aToTwig = array(
            'MESSAGE_TYPE'  => $sType,
            'MESSAGES'      => $uMsg,
            'REDIRECT_URL'  => $sRedirectUri,
            'REDIRECT_TIME' => $iRedirectTime,
            'USE_REDIRECT'  => $bUseRedirect
        );
        $this->getThemeFile('_alerts.inc.twig', $aToTwig);
        if ($bAutoFooter == true) {
            if (method_exists($this, "print_footer")) {
                $this->print_footer();
            }
            exit();
        }
    }

    public function getThemeFile(string $sTplName = '', array $aToTwig = []): void
    {
        $aTemplateLocs = array();
        $aCheckDirs = array(
            THEME_PATH . '/templates/',
            WB_PATH . '/templates/theme_fallbacks/templates/'
        );
        foreach ($aCheckDirs as $dir) {
            if (is_dir($dir)) {
                $aTemplateLocs[] = $dir;
            }
        }
        $oTwig     = getTwig($aTemplateLocs);
        $oTemplate = $oTwig->load($sTplName);
        $oTemplate->display($aToTwig);
    }

    /**
     * Print an error message with a "back" button to a specified page.
     *
     * @param mixed  $uMsg          Single string or array of messages
     * @param string $sRedirectUri  URL for the back button
     * @param bool   $bAutoFooter
     */
    public function print_error(array|string $uMsg, string $sRedirectUri = 'index.php', bool $bAutoFooter = true): void
    {
        // Errors are sticky — never auto-redirect, only show a back-button if a URL is given.
        $this->messageBox($uMsg, 'error', $sRedirectUri, $bAutoFooter, false);
    }

    /**
     * Validate and send an email via PHPMailer/Mailer.
     *
     * @param string $fromaddress
     * @param string $toaddress
     * @param string $subject
     * @param string $message
     * @param string $fromname
     * @return bool
     */
    public function mail(string $fromaddress, string $toaddress, string $subject, string $message, string $fromname = ''): bool
    {
        $fromaddress = preg_replace('/[\r\n]/', '', $fromaddress);
        $toaddress   = preg_replace('/[\r\n]/', '', $toaddress);
        $subject     = preg_replace('/[\r\n]/', '', $subject);

        $myMail = new Mailer();

        if ($fromaddress != '') {
            if ($fromname != '') {
                $myMail->FromName = $fromname;
            }
            $myMail->From = $fromaddress;
            $myMail->AddReplyTo($fromaddress);
        }

        $myMail->AddAddress($toaddress);
        $myMail->Subject  = $subject;
        $myMail->Body     = nl2br($message);
        $myMail->AltBody  = strip_tags($message);

        return $myMail->Send() ? true : false;
    }

    /**
     * Resolve the absolute path of a theme file using a fallback mechanism.
     *
     * Checks the active theme directory first, then falls back to
     * /templates/theme_fallbacks/. Terminates with die() if the file
     * is missing in both locations.
     *
     * @param  string $sThemeFile  Filename including extension (e.g. 'layout.twig')
     * @return string              Absolute server path to the resolved file
     */
    public function correct_theme_source(string $sThemeFile = 'start.htt') : string
    {
        $sSysThemeFile = WB_PATH . '/templates/theme_fallbacks/templates/' . $sThemeFile;
        $sOverrideFile = THEME_PATH . '/templates/' . $sThemeFile;
        if (file_exists($sOverrideFile)) {
            return $sOverrideFile;
        } elseif (file_exists($sSysThemeFile)) {
            return $sSysThemeFile;
        } else {
            die('Following Backend Theme file is missing: ' . $sThemeFile);
        }
    }

    /**
     * Check if a folder name contains no invalid characters.
     *
     * @param  string $str
     * @return bool
     */
    public function checkFolderName(string $str): bool
    {
        return !(preg_match('#\^|\\\|\/|\.|\?|\*|"|\'|\<|\>|\:|\|#i', $str) ? true : false);
    }

    /**
     * Verify that the given path is within the base directory (document root).
     *
     * @param  string $sCurrentPath
     * @param  string $sBaseDir
     * @return string|false  Resolved path, or false if outside base dir
     */
    public function checkpath(string $sCurrentPath, string $sBaseDir = WB_PATH): string|false
    {
        $sCurrentPath = rawurldecode($sCurrentPath);
        $sCurrentPath = realpath($sCurrentPath);
        $sBaseDir     = realpath($sBaseDir);

        $pos = stripos($sCurrentPath, $sBaseDir);

        if ($pos === false) {
            return false;
        } elseif ($pos == 0) {
            return $sCurrentPath;
        } else {
            return false;
        }
    }

    /**
     * Registers module files (CSS, JS, jQuery, system variables) and inserts them
     * into the DOM using the Insert class (I::) methods.
     *
     * This is the main public entry point for modules/themes to register their assets.
     *
     * @param string $modfileType  css|js|jquery|js_sysvars
     * @param string $context      'frontend' or 'backend'
     * @return void
     */
    public function registerModfiles(string $modfileType = 'css', string $context = 'frontend'): void
    {
        $toInsert = $this->collectModfiles($context);

        $modfileType = strtolower(trim($modfileType));

        switch ($modfileType) {

            case 'css':
                if (!empty($toInsert['css']) && is_array($toInsert['css'])) {
                    foreach ($toInsert['css'] as $cssFile) {
                        I::insertCssFile($cssFile, 'HEAD MODFILES');
                    }
                }
                break;

            case 'jquery':
                $jqueryFiles = [
                    WB_URL . '/include/jquery/jquery-min.js',
                    WB_URL . '/include/jquery/jquery-insert.js',
                    WB_URL . '/include/jquery/jquery-migrate-min.js',
                ];

                $themeFile = WB_URL . '/modules/jquery/jquery_theme.js';
                if (file_exists(str_replace(WB_URL, WB_PATH, $themeFile))) {
                    $jqueryFiles[] = $themeFile;
                } else {
                    $jqueryFiles[] = WB_URL . '/include/jquery/jquery_theme.js';
                }

                $templateJquery = TEMPLATE_DIR . '/jquery_frontend.js';
                if (file_exists(str_replace(WB_URL, WB_PATH, $templateJquery))) {
                    $jqueryFiles[] = $templateJquery;
                }

                foreach ($jqueryFiles as $jsFile) {
                    I::insertJsFile($jsFile, 'HEAD MODFILES');
                }
                break;

            case 'js':
                $jsSysvars = $this->buildJsSystemVariables();
                I::insertJsCode($jsSysvars, 'HEAD TOP+', 'js_sysvars');

                if (!empty($toInsert['js_head']) && is_array($toInsert['js_head'])) {
                    foreach ($toInsert['js_head'] as $jsFile) {
                        I::insertJsFile($jsFile, 'HEAD MODFILES');
                    }
                }

                if (!empty($toInsert['js_body']) && is_array($toInsert['js_body'])) {
                    foreach ($toInsert['js_body'] as $jsFile) {
                        I::insertJsFile($jsFile, 'BODY BTM-');
                    }
                }
                break;

            case 'js_sysvars':
                // System variables are already handled in the 'js' case.
                // This case exists only for backward compatibility.
                break;

            default:
                // Unknown modfile type → do nothing (silent)
                break;
        }
    }

    /**
     * Build the JavaScript system variables block inserted into <head>.
     *
     * @return string  JavaScript code with variable declarations
     */
    private function buildJsSystemVariables(): string
    {
        $js = "\t\t";

        if (defined('URL_VAR_COMPATIBILITY_MODE') && URL_VAR_COMPATIBILITY_MODE === true) {
            $js .= "var URL = WB_URL = '" . WB_URL . "';\n";
        } else {
            $js .= "var WB_URL = '" . WB_URL . "';\n";
        }

        if (defined('LANGUAGE')) {
            $js .= "\t\tvar LANGUAGE     = '" . strtolower(LANGUAGE) . "';\n";
        }

        if (defined('PAGE_ID')) {
            $js .= "\t\tvar PAGE_ID      = " . (int) PAGE_ID . ";\n";
        } elseif (isset($_REQUEST['page_id']) && is_numeric($_REQUEST['page_id'])) {
            $js .= "\t\tvar PAGE_ID      = " . (int) $_REQUEST['page_id'] . ";\n";
        }

        if (isset($_REQUEST['section_id']) && is_numeric($_REQUEST['section_id'])) {
            $js .= "\t\tvar SECTION_ID   = " . (int) $_REQUEST['section_id'] . ";\n";
        }

        if (defined('TEMPLATE_DIR')) {
            $js .= "\t\tvar TEMPLATE_DIR = '" . TEMPLATE_DIR . "';\n";
        }

        if (defined('BACKEND_CONTEXT')) {
            if (defined('THEME_URL')) {
                $js .= "\t\tvar THEME_URL    = '" . THEME_URL . "';\n";
            }
            if (defined('ADMIN_URL')) {
                $js .= "\t\tvar ADMIN_URL    = '" . ADMIN_URL . "';\n";
            }
        }

        $sessionTimeout = $this->get_session_timeout();
        $js .= "\t\tvar SESSION_TIMEOUT = '" . $sessionTimeout . "';\n";

        return $js;
    }

    /**
     * Collect module directories and their modfiles for registerModfiles().
     *
     * @param  string $context  'frontend' or 'backend'
     * @return array
     */
    private function collectModfiles(string $context = 'frontend'): array
    {
        $toInsert = [];
        $modules  = [];

        // 1. Snippets — frontend only
        if (defined('FRONTEND_CONTEXT')) {
            $modules = array_merge($modules, $this->db->fetchAll(
                "SELECT `directory` AS `module_dir`
                 FROM `{TP}addons`
                 WHERE `function` LIKE '%snippet%'",
                []
            ));
        }

        // 2. Page-type modules (backend only)
        $pageId = null;
        if (defined('PAGE_ID')) {
            $pageId = PAGE_ID;
        } elseif (isset($_REQUEST['page_id']) &&
                  strposm($_SERVER['PHP_SELF'], ['pages/sections.php', 'pages/settings.php']) === false) {
            $pageId = (int) $_REQUEST['page_id'];
        }

        if ($pageId !== null && defined('BACKEND_CONTEXT')) {
            $modules = array_merge($modules, $this->db->fetchAll(
                "SELECT `module` AS `module_dir`
                 FROM `{TP}sections`
                 WHERE `page_id` = ?",
                [$pageId]
            ));
        }

        // 3. Tools (backend)
        if (!empty($_GET['tool'])) {
            $modules = array_merge($modules, $this->db->fetchAll(
                "SELECT `directory` AS `module_dir`
                 FROM `{TP}addons`
                 WHERE `function` LIKE '%tool%'
                   AND `directory` = ?",
                [$_GET['tool']]
            ));
        }

        foreach ($modules as $row) {
            $moduleDir = $row['module_dir'] ?? '';
            if (empty($moduleDir)) {
                continue;
            }

            $filesByType = $this->retrieveModfilesFromDir($moduleDir, $context);

            foreach ($filesByType as $type => $wrappedFiles) {
                foreach ($wrappedFiles as $wrapped) {
                    $toInsert[$type][] = $wrapped[0];
                }
            }
        }

        return $toInsert;
    }

    /**
     * Retrieve modfiles (css, js_head, js_body) from a single module directory.
     *
     * Returns files in a backward-compatible format so that existing code
     * like block_contents() and get_section_content() continues to work.
     * Each file is wrapped in an array — $sFile[0] contains the actual URL.
     *
     * @param  string $moduleDir  Module directory name
     * @param  string $context    'frontend' or 'backend'
     * @return array
     */
    public function retrieveModfilesFromDir(string $moduleDir, string $context = 'frontend'): array
    {
        $collection = [
            'css'     => [],
            'js_head' => [],
            'js_body' => []
        ];

        $modPath = '/modules/' . $moduleDir . '/';

        $addFile = function (string $relativePath, string $type) use (&$collection, $modPath): void {
            $fullPath = WB_PATH . $modPath . $relativePath;
            $fullUrl  = WB_URL  . $modPath . $relativePath;

            if (file_exists(str_replace('%s', '.override', $fullPath))) {
                $collection[$type][] = str_replace('%s', '.override', $fullUrl);
            }

            if (file_exists(str_replace('%s', '', $fullPath))) {
                $collection[$type][] = str_replace('%s', '', $fullUrl);
            }
        };

        $addFile($context . '%s.css',     'css');
        $addFile($context . '%s.js',      'js_head');
        $addFile($context . '_body%s.js', 'js_body');

        $result = [];
        foreach ($collection as $type => $files) {
            $result[$type] = array_map(fn($url) => [$url], $files);
        }

        return $result;
    }

    /**
     * Get the configured session timeout value in seconds.
     *
     * @return string
     */
    public function get_session_timeout(): string
    {
        if ($sSessionTimeout = Settings::get("wb_session_timeout")) {
        } elseif ($sSessionTimeout = Settings::get("wb_secform_timeout")) {
        } else {
            $sSessionTimeout = "7200";
        }
        return $sSessionTimeout;
    }

    /**
     * Return an array of all sections for a given page.
     *
     * @param  int|null $iPageID
     * @param  bool     $bExcludeNonPublicised  Skip sections outside their publication window
     * @return array
     */
    public function get_page_sections(?int $iPageID = null, bool $bExcludeNonPublicised = false): array
    {
        $aSections = array();

        if ($iPageID == null) {
            global $page_id;
            $iPageID = defined('PAGE_ID') ? PAGE_ID : $page_id;
        } else {
            $iPageID = (int)$iPageID;
        }

        if ($iPageID > 0) {
            $sSql = 'SELECT * FROM `{TP}sections` WHERE `page_id` = ? ORDER BY `position`';
            if ($resSections = $this->db->query($sSql, [$iPageID])) {
                while ($rec = $resSections->fetchRow(MYSQLI_ASSOC)) {
                    if ($bExcludeNonPublicised == true) {
                        $iNowTime = time();
                        if (!(($iNowTime <= $rec['publ_end'] || $rec['publ_end'] == 0) && ($iNowTime >= $rec['publ_start'] || $rec['publ_start'] == 0))) {
                            continue;
                        }
                    }
                    $aSections[$rec['section_id']] = $rec;
                    $aSections[$rec['section_id']]['module_name'] = $this->get_module_name($rec['module']);
                }
            }
        }
        return $aSections;
    }

    /**
     * Resolve a string value (name or description) for a module.
     *
     * Lookup order:
     *   1. languages/LANGUAGE.php — variable extraction via get_variable_content()
     *   2. languages.php (single-file format) — array key lookup
     *   3. info.php — variable extraction
     *   4. {TP}addons table column fallback
     *
     * @param  string   $modDir    Module directory name
     * @param  string[] $varNames  Variable names to try in order (first match wins)
     * @param  string   $dbColumn  Column to read from the addons table as last resort
     * @return string
     */
    private function _resolveModuleString(string $modDir, array $varNames, string $dbColumn): string
    {
        $modBase = WB_PATH . '/modules/' . $modDir;
        $value   = '';

        // 1. languages/LANGUAGE.php
        $langFile = $modBase . '/languages/' . LANGUAGE . '.php';
        if (file_exists($langFile)) {
            $data  = @file_get_contents($langFile);
            foreach ($varNames as $var) {
                $temp = get_variable_content($var, $data, true, false);
                if ($temp !== false && $temp !== '') { $value = $temp; break; }
            }
        }

        // 2. languages.php (single-file format)
        if ($value === '') {
            $singleFile = $modBase . '/languages.php';
            if (is_file($singleFile)) {
                $all = include $singleFile;
                if (is_array($all)) {
                    $langData = array_merge($all['EN'] ?? [], $all[LANGUAGE] ?? []);
                    foreach ($varNames as $var) {
                        if (!empty($langData[$var])) { $value = (string)$langData[$var]; break; }
                    }
                }
            }
        }

        // 3. info.php
        if ($value === '') {
            $infoFile = $modBase . '/info.php';
            if (file_exists($infoFile)) {
                $data = @file_get_contents($infoFile);
                foreach ($varNames as $var) {
                    $temp = get_variable_content($var, $data, true, false);
                    if ($temp !== false && $temp !== '') { $value = $temp; break; }
                }
            }
        }

        // 4. addons table
        if ($value === '') {
            $value = (string)($this->db->fetchValue(
                "SELECT `$dbColumn` FROM `{TP}addons` WHERE `directory` = ?",
                [$modDir]
            ) ?? '');
        }

        return $value;
    }

    /**
     * Get the display name of a module, resolved from language files or the addons table.
     *
     * @param  string $modDir        Module directory name
     * @param  bool   $showOriginal  Append the original DB name in parentheses
     * @param  string $hem           Format string for original name (default: ' (%s)')
     * @param  string $modType       'page', 'tool', 'snippet', ...
     * @return string
     */
    public function get_module_name(
        string $modDir = '',
        bool   $showOriginal = false,
        string $hem          = ' (%s)',
        string $modType      = 'page'
    ): string {
        if (empty($modDir)) return '';

        $varNames = $modType !== 'page'
            ? [$modType . '_name', 'module_name']
            : ['module_name'];

        $moduleName = $this->_resolveModuleString($modDir, $varNames, 'name');

        if ($moduleName === '') $moduleName = $modDir;

        if ($showOriginal) {
            $original = (string)($this->db->fetchValue(
                "SELECT `name` FROM `{TP}addons` WHERE `directory` = ?",
                [$modDir]
            ) ?? $modDir);
            $moduleName .= sprintf($hem, $original);
        }

        return $moduleName;
    }

    /**
     * Get the description of a module, resolved from language files or the addons table.
     *
     * @param  string $modDir   Module directory name
     * @param  string $modType  'page', 'tool', 'snippet', ...
     * @return string
     */
    public function get_module_description(string $modDir = '', string $modType = 'page'): string
    {
        if (empty($modDir)) return '';

        $varNames = ['module_description'];
        if ($modType !== 'page') $varNames[] = $modType . '_description';

        $description = $this->_resolveModuleString($modDir, $varNames, 'description');

        return str_replace('{WB_URL}', WB_URL, $description);
    }

    /**
     * @deprecated No-op — PDO handles escaping automatically.
     *             Kept for backward compatibility with older modules.
     *
     * @param  string $input
     * @return string  unchanged
     */
    public function add_slashes(mixed $input): mixed
    {
        if (defined('SQL_DEBUG') && SQL_DEBUG) {
            trigger_error(
                'add_slashes() was called but ignored because the PDO database class is active. ' .
                'PDO handles escaping automatically.',
                E_USER_NOTICE
            );
        }
        return $input;
    }

    /**
     * @deprecated No-op — kept for backward compatibility with older modules.
     *
     * @param  mixed $input
     * @return mixed  unchanged
     */
    public function strip_slashes(mixed $input): mixed
    {
        return $input;
    }
}
