<?php
/**
 *
 * @category        backend,hidden
 * @package         OpF Simple Backend
 * @version         1.3.0
 * @authors         Martin Hecht (mrbaseman)
 * @copyright       (c) 2018, Martin Hecht (mrbaseman)
 * @link            https://forum.wbce.org/viewtopic.php?id=176
 * @license         GNU GPL2 (or any later version)
 * @platform        WBCE 1.2.x
 * @requirements    OutputFilter Dashboard 1.5.x and PHP 5.4 or higher
 *
 **/


/* -------------------------------------------------------- */
// Must include code to stop this file being accessed directly
if(!defined('WB_PATH')) {
        // Stop this file being access directly
        if(!headers_sent()) header("Location: ../index.php",TRUE,301);
        die('<head><title>Access denied</title></head><body><h2 style="color:red;margin:3em auto;text-align:center;">Cannot access this file directly</h2></body></html>');
}
/* -------------------------------------------------------- */


// Module description
$module_description = 'A tool to configure the basic output filter of WBCE CMS';

// Headings and text outputs
$OPF['HEADING'] = 'Options: Output Filter';
$OPF['HOWTO'] = 'You can configure the output filtering with the options below.';
$OPF['WARNING'] = '';

// Text and captions of form elements
$OPF['BASIC_CONF'] = 'Basic configuration';
$OPF['SYS_REL'] = 'Frontend output with  relative URLs';
$OPF['ENABLED'] = 'Enabled';
$OPF['DISABLED'] = 'Disabled';

$OPF['REPLACEMENT_CONF']= 'Email replacements';

$OPF['DROPLETS'] = 'Droplets filter (whithout this droplets won\'t work)';
$OPF['WBLINK'] = 'WB-Link Filter (replace [wblinkXX] with URL of the page)';
$OPF['AUTO_PLACEHOLDER'] = 'Add placeholder for moving JS, CSS and more around';
$OPF['MOVE_STUFF'] = 'CSS, JS, and more will be moved to placeholders';
$OPF['REPLACE_STUFF'] = 'Relplace title keywords or description by modules';
$OPF['SHORT_URL'] = 'Use short url filter (no /pages, no .php - htaccess has to be prepared for that)';
$OPF['CSS_TO_HEAD'] = 'Move CSS to head';
$OPF['REMOVE_SYSTEM_PH'] = 'Remove placesholders(PH) generated by core filters.';



