<?php defined('WB_PATH') or header("Location: ../index.php", true, 301); ?>
<!-- [subject]WBCE CMS test email[/subject] -->
Hello {{WBMAILER_DEFAULT_SENDERNAME}},

this email was generated by your Website "{{LOGIN_WEBSITE_TITLE}}" [{{WB_URL}}] for testing purposes.
Since you recieved it, it seems as if the email configuration is working as expected.
Feel free to delete this email.


------------------------------------------------------------------------------------------
   This email was sent {{DATE}} at {{TIME}}.
------------------------------------------------------------------------------------------