<?php
/**
 * modules/asset_optimizer/languages.php
 *
 * Lang::loadLanguage() merges the EN block first as the base, then overlays the
 * active locale. EN must be complete; every other locale only needs the keys it
 * translates — anything missing falls back to EN.
 *
 * EN and DE are complete. NL / PL / NO / FR / IT / ES / RU translate the visible
 * labels (tabs, cards, columns, buttons, badges); the longer help paragraphs
 * fall back to EN.
 */

return [

    // ═══════════════════════════════════════════════════════════════════ EN ═══
    'EN' => [
        'module_name'        => 'AssetQueue Optimizer',
        'module_description' => 'Manage WBCE\'s asset pipeline: CSS/JS minification, bundling and browser cache-busting. Asset and Font Cache-status lookup.',

        'TXT' => [
            // ── Chrome ─────────────────────────────────────────────────────
            'TAB_SETTINGS' => 'Settings',
            'TAB_CACHE'    => 'Cache & status',
            'TAB_DOCS'     => 'Documentation',
            'SAVE'         => 'Save settings',
            'ENABLED'      => 'On',
            'DISABLED'     => 'Off',

            // ── Documentation tab ─────────────────────────────────────────
            'DOC_GUIDE'         => 'Guide',
            'DOC_EMBED'         => 'Assets in templates',
            'DOC_FONTS'         => 'Web fonts',
            'DOC_REFERENCE'     => 'Full reference',
            'DOC_ON_THIS_PAGE'  => 'On this page',
            'DOC_UNAVAILABLE'   => 'Install the MarkdownWbce module to read the documentation here in the backend. The source file is on disk at:',
            'DOC_MISSING'       => 'Documentation file not found: %s',
            'DOC_SOURCE'       => 'Source:',

            // ── Settings: intro + config.php notice ────────────────────────
            'SETTINGS_INTRO' => 'These switches control framework/Assets/AssetQueue.php — the queue that collects every stylesheet, script, font and meta tag on a page and injects it at the right place in the HTML. All values become PHP constants at boot; a change takes effect on the next page load.',
            'STORAGE_NOTE'   => 'The minification switches are written to var/config_constants.ini.php (nothing else touches them). The cache-busting pair is written to the settings table — the same rows the "Assets Cache Busting" filter in Outputfilter Dashboard uses, so there is one value, not two.',

            'PINNED_TITLE' => '%d constant(s) defined in config.php',
            'PINNED_BODY'  => 'A value in config.php always wins — over the ini file and the settings table — so it cannot be changed here, and it is easy to lose during an update. Move these to var/config_constants.ini.php and this tool will manage them: %s',
            'LOCKED_NOTE'  => 'Defined in config.php — read-only here.',
            'LEGACY_DEBUG_NOTE' => 'Note: the legacy constant %s is still defined. It is honoured, but ASSETS_MINIFY_DEBUG is the canonical name now — move it over when convenient.',

            // ── Cards ─────────────────────────────────────────────────────
            'CARD_MINIFY'   => 'Minification',
            'CARD_BUST'     => 'Browser cache busting',
            'CARD_ADVANCED' => 'Advanced',
            'FOOT_INI'      => 'Written to var/config_constants.ini.php — update-safe.',
            'FOOT_DB'       => 'Written to the settings table — shared with Outputfilter Dashboard.',
            'BUST_INTRO'    => 'Appends each file\'s modification time to its URL (main.css?1712345678) so browsers fetch a fresh copy the moment a file changes. Applies to local files and same-origin URLs; cross-origin CDN URLs are left alone.',

            // ── Minification switches ─────────────────────────────────────
            'MINIFY_CSS_LABEL' => 'Minify CSS',
            'MINIFY_CSS_DESC'  => 'Strips comments and whitespace from every local stylesheet — combined bundles and stand-alone files — and caches the result. External (CDN) stylesheets are never touched. The cache is rebuilt when a source file changes, or when you flip this switch.',

            'MINIFY_JS_LABEL' => 'Minify JavaScript',
            'MINIFY_JS_DESC'  => 'The same for scripts — comments and whitespace out, smaller file, identical behaviour.',

            'MINIFY_USE_SUFFIX_LABEL' => 'Keep the .min suffix',
            'MINIFY_USE_SUFFIX_DESC'  => 'Whether cached files carry a .min marker in their name (wbcetik-css-main.min.css vs wbcetik-css-main.css). Purely cosmetic. Changing this setting rewrites the cache.',

            'ASSETS_MINIFY_DEBUG_LABEL' => 'Developer source view',
            'ASSETS_MINIFY_DEBUG_DESC'  => 'While you are logged in, turns off both minification and bundling so browser DevTools shows the original, individually-named source files. Every other visitor keeps receiving the optimised output, so this is safe to leave on — it never changes what the public sees.',

            // ── Cache-busting switches ───────────────────────────────────
            'OPF_ASSETS_CACHE_BUSTING_LABEL' => 'Front end',
            'OPF_ASSETS_CACHE_BUSTING_DESC'  => 'Cache busting for the public site.',

            'OPF_ASSETS_CACHE_BUSTING_BE_LABEL' => 'Back end',
            'OPF_ASSETS_CACHE_BUSTING_BE_DESC'  => 'Cache busting for the admin backend only, separate from the public site. Adjustable only while front-end cache busting is off — otherwise the backend follows the front end.',
            'BUST_BE_FOLLOWS_FE'                => 'Follows the front-end switch while that is on. Turn front-end cache busting off to set this separately.',

            // ── Advanced ────────────────────────────────────────────────

            'MINIFY_ASSETS_DIR_LABEL' => 'Cache directory',
            'MINIFY_ASSETS_DIR_DESC'  => 'Absolute filesystem path where bundles and minified files are written. Leave empty for the default cache/assets/. Must be writable by the web server and reachable under your document root.',
            'MINIFY_ASSETS_DIR_PH'    => '/absolute/path/to/cache/  — empty for the default',
            'DIR_OVERRIDE'           => 'Set a custom directory',

            'ASSET_QUEUE_DEBUG_LABEL' => 'Admin console errors',
            'ASSET_QUEUE_DEBUG_DESC'  => 'When on, AssetQueue prints a console.error() block for logged-in administrators if it hits a problem while assembling a page. Its own switch — independent of the global WBCE_DEBUG (which, when on, enables it too). Keep it off on a live site.',

            // ── Cache & status ─────────────────────────────────────────
            'CACHE_INTRO' => 'The queue writes combined bundles and minified copies into the asset cache, and self-hosted web fonts into cache/fonts/. Clearing either is always safe — the next page load regenerates whatever it needs.',

            'STAT_FILES'      => 'cached files',
            'STAT_ORIGINAL'   => 'original',
            'STAT_OPTIMISED'  => 'optimised',
            'STAT_GZIP'       => 'gzipped est.',
            'STAT_SAVED'      => 'saved',
            'STAT_BUILT'      => 'last build',

            'CLEAR_ASSETS'  => 'Clear asset cache',
            'CLEAR_FONTS'   => 'Clear font cache',
            'CLEAR_ASSETS_CONFIRM' => 'Clear the asset cache? Bundles and minified files are rebuilt on the next page load.',
            'CLEAR_FONTS_CONFIRM'  => 'Clear the web-font cache? Fonts are re-downloaded on the next page load.',
            'ASSET_CACHE_CLEARED' => 'Asset cache cleared. Bundles and minified files rebuild on the next page load.',
            'FONT_CACHE_CLEARED'  => 'Web-font cache cleared.',
            'MIGRATED_TO_DB'      => 'Moved %s out of config_constants.ini.php into the settings table, where this tool and Outputfilter Dashboard both manage it.',

            'CARD_BUNDLES'  => 'Bundles',
            'CARD_MINFILES' => 'Minified files',
            'CARD_FONTS'    => 'Self-hosted web fonts',
            'CARD_HEALTH'   => 'Health checks',

            'COL_FILE'     => 'File',
            'COL_SOURCES'  => 'Sources',
            'COL_ORIGINAL' => 'Original',
            'COL_MINIFIED' => 'Minified',
            'COL_GZIP'     => 'gzip est.',
            'COL_SAVED'    => 'Saved',
            'COL_BUILT'    => 'Built',
            'COL_SIZE'     => 'Size',
            'COL_CACHED'   => 'Cached',


            'BUNDLE_SOURCES'   => '%d files',
            'SOURCE_DELETED'   => 'source deleted',
            'CACHE_EMPTY'      => 'The asset cache is empty — nothing has been built yet.',
            'FONTS_EMPTY'      => 'No web fonts are self-hosted. Templates load fonts with insertWebFont().',
            'NOT_MINIFIED'     => 'not minified',

            // ── Health-check strings ──────────────────────────────────
            'CHK_ASSETS_DIR'    => 'Asset cache directory is writable',
            'CHK_ASSETS_DIR_T'  => 'The web server can create and replace files in %s.',
            'CHK_FONTS_DIR'     => 'Font cache directory is writable',
            'CHK_FONTS_DIR_T'   => 'Self-hosted fonts can be downloaded into %s.',
            'CHK_MINLIB'        => 'JavaScript minifier',
            'CHK_MINLIB_NO'     => 'matthiasmullie/minify is not installed. Drop it into include/matthiasmullie/ for full JS minification.',
            'CHK_CURL'          => 'cURL is available',
            'CHK_CURL_T'        => 'Required to self-host web fonts via insertWebFont().',
            'CHK_PINNED'        => '%d constant(s) pinned in config.php',
            'CHK_PINNED_T'      => 'Move these to var/config_constants.ini.php so this tool can manage them and an update cannot drop them: %s.',
        ],

        'MSG' => [],
    ],

    // ═══════════════════════════════════════════════════════════════════ DE ═══
    'DE' => [
        'module_name'        => 'AssetQueue Optimizer',
        'module_description' => 'Verwaltet WBCEs Asset-Pipeline: CSS-/JS-Minifizierung, Bündelung und Browser-Cache-Busting. Übersicht des Asset- und Font-Caches.',

        'TXT' => [
            'TAB_SETTINGS' => 'Einstellungen',
            'TAB_CACHE'    => 'Cache & Status',
            'TAB_DOCS'     => 'Dokumentation',
            'SAVE'         => 'Einstellungen speichern',
            'ENABLED'      => 'An',
            'DISABLED'     => 'Aus',

            'DOC_GUIDE'         => 'Anleitung',
            'DOC_EMBED'         => 'Assets im Template',
            'DOC_FONTS'         => 'Web-Fonts',
            'DOC_REFERENCE'     => 'Referenz',
            'DOC_ON_THIS_PAGE'  => 'Auf dieser Seite',
            'DOC_UNAVAILABLE'   => 'Installiere das Modul MarkdownWbce, um die Dokumentation hier im Backend zu lesen. Die Quelldatei liegt unter:',
            'DOC_MISSING'       => 'Dokumentationsdatei nicht gefunden: %s',
            'DOC_SOURCE'       => 'Quelle:',

            'SETTINGS_INTRO' => 'Diese Schalter steuern framework/Assets/AssetQueue.php — die Queue, die alle Stylesheets, Skripte, Fonts und Meta-Tags einer Seite sammelt und an der richtigen Stelle im HTML einfügt. Alle Werte werden beim Start zu PHP-Konstanten; eine Änderung wirkt beim nächsten Seitenaufruf.',
            'STORAGE_NOTE'   => 'Die Minifizierungs-Schalter werden in var/config_constants.ini.php geschrieben (nichts anderes fasst sie an). Das Cache-Busting-Paar landet in der settings-Tabelle — dieselben Zeilen, die der Filter „Assets Cache Busting" im Outputfilter Dashboard nutzt, also gibt es einen Wert, nicht zwei.',

            'PINNED_TITLE' => '%d Konstante(n) in config.php definiert',
            'PINNED_BODY'  => 'Ein Wert in config.php gewinnt immer — gegenüber der ini-Datei und der settings-Tabelle — und lässt sich hier nicht ändern; außerdem geht er bei einem Update leicht verloren. Verschiebe diese nach var/config_constants.ini.php, dann verwaltet dieses Tool sie: %s',
            'LOCKED_NOTE'  => 'In config.php definiert — hier nur lesbar.',
            'LEGACY_DEBUG_NOTE' => 'Hinweis: Die alte Konstante %s ist noch definiert. Sie wird beachtet, aber ASSETS_MINIFY_DEBUG ist jetzt der kanonische Name — bei Gelegenheit umstellen.',

            'CARD_MINIFY'   => 'Minifizierung',
            'CARD_BUST'     => 'Browser-Cache-Busting',
            'CARD_ADVANCED' => 'Erweitert',
            'FOOT_INI'      => 'Wird in var/config_constants.ini.php geschrieben — updatesicher.',
            'FOOT_DB'       => 'Wird in die settings-Tabelle geschrieben — gemeinsam mit dem Outputfilter Dashboard.',
            'BUST_INTRO'    => 'Hängt die Änderungszeit jeder Datei an ihre URL an (main.css?1712345678), damit Browser sofort eine frische Kopie laden, sobald sich eine Datei ändert. Gilt für lokale Dateien und gleichdomänige URLs; fremde CDN-URLs bleiben unberührt.',

            'MINIFY_CSS_LABEL' => 'CSS minifizieren',
            'MINIFY_CSS_DESC'  => 'Entfernt Kommentare und Leerraum aus jedem lokalen Stylesheet — kombinierte Bundles und Einzeldateien — und legt das Ergebnis im Cache ab. Externe (CDN-)Stylesheets bleiben unangetastet. Der Cache wird neu gebaut, sobald sich eine Quelldatei ändert oder du diesen Schalter umlegst.',

            'MINIFY_JS_LABEL' => 'JavaScript minifizieren',
            'MINIFY_JS_DESC'  => 'Dasselbe für Skripte — Kommentare und Leerraum raus, kleinere Datei, gleiches Verhalten.',

            'MINIFY_USE_SUFFIX_LABEL' => '.min-Suffix behalten',
            'MINIFY_USE_SUFFIX_DESC'  => 'Ob Cache-Dateien eine .min-Kennung im Namen tragen (wbcetik-css-main.min.css statt wbcetik-css-main.css). Rein kosmetisch. Bei Änderung dieser Einstellung wird der Cache neu geschrieben.',

            'ASSETS_MINIFY_DEBUG_LABEL' => 'Entwickler-Quellansicht',
            'ASSETS_MINIFY_DEBUG_DESC'  => 'Solange du angemeldet bist, schaltet dies Minifizierung und Bündelung aus, damit die Browser-DevTools die ursprünglichen, einzeln benannten Quelldateien zeigen. Alle anderen Besucher erhalten weiter die optimierte Ausgabe — es ist also unbedenklich, das aktiviert zu lassen; für die Öffentlichkeit ändert sich nichts.',

            'OPF_ASSETS_CACHE_BUSTING_LABEL' => 'Frontend',
            'OPF_ASSETS_CACHE_BUSTING_DESC'  => 'Cache-Busting für die öffentliche Website.',

            'OPF_ASSETS_CACHE_BUSTING_BE_LABEL' => 'Backend',
            'OPF_ASSETS_CACHE_BUSTING_BE_DESC'  => 'Cache-Busting nur fürs Admin-Backend, getrennt von der öffentlichen Seite. Nur einstellbar, solange Frontend-Cache-Busting aus ist — sonst folgt das Backend dem Frontend.',
            'BUST_BE_FOLLOWS_FE'                => 'Folgt dem Frontend-Schalter, solange der an ist. Für eine eigene Einstellung zuerst das Frontend-Cache-Busting ausschalten.',


            'MINIFY_ASSETS_DIR_LABEL' => 'Cache-Verzeichnis',
            'MINIFY_ASSETS_DIR_DESC'  => 'Absoluter Dateisystempfad, in den Bundles und minifizierte Dateien geschrieben werden. Leer lassen für den Standard cache/assets/. Muss vom Webserver beschreibbar und unter deinem Document-Root erreichbar sein.',
            'MINIFY_ASSETS_DIR_PH'    => '/absoluter/pfad/zum/cache/  — leer für den Standard',
            'DIR_OVERRIDE'           => 'Abweichenden Ordner festlegen',

            'ASSET_QUEUE_DEBUG_LABEL' => 'Admin-Konsolenfehler',
            'ASSET_QUEUE_DEBUG_DESC'  => 'Wenn an, gibt die AssetQueue für angemeldete Administratoren einen console.error()-Block aus, falls beim Zusammenbauen einer Seite ein Problem auftritt. Ein eigener Schalter — unabhängig vom globalen WBCE_DEBUG (das ihn, wenn an, ebenfalls aktiviert). Auf einer Live-Seite ausgeschaltet lassen.',

            'CACHE_INTRO' => 'Die Queue schreibt kombinierte Bundles und minifizierte Kopien in den Asset-Cache und selbst gehostete Web-Fonts nach cache/fonts/. Beides zu leeren ist jederzeit gefahrlos — der nächste Seitenaufruf erzeugt neu, was gebraucht wird.',

            'STAT_FILES'      => 'Dateien im Cache',
            'STAT_ORIGINAL'   => 'Original',
            'STAT_OPTIMISED'  => 'optimiert',
            'STAT_GZIP'       => 'gzip geschätzt',
            'STAT_SAVED'      => 'gespart',
            'STAT_BUILT'      => 'letzter Build',

            'CLEAR_ASSETS'  => 'Asset-Cache leeren',
            'CLEAR_FONTS'   => 'Font-Cache leeren',
            'CLEAR_ASSETS_CONFIRM' => 'Asset-Cache leeren? Bundles und minifizierte Dateien werden beim nächsten Seitenaufruf neu gebaut.',
            'CLEAR_FONTS_CONFIRM'  => 'Web-Font-Cache leeren? Fonts werden beim nächsten Seitenaufruf neu heruntergeladen.',
            'ASSET_CACHE_CLEARED' => 'Asset-Cache geleert. Bundles und minifizierte Dateien werden beim nächsten Seitenaufruf neu gebaut.',
            'FONT_CACHE_CLEARED'  => 'Web-Font-Cache geleert.',
            'MIGRATED_TO_DB'      => '%s aus config_constants.ini.php in die settings-Tabelle verschoben, wo dieses Tool und das Outputfilter Dashboard sie gemeinsam verwalten.',

            'CARD_BUNDLES'  => 'Bundles',
            'CARD_MINFILES' => 'Minifizierte Dateien',
            'CARD_FONTS'    => 'Selbst gehostete Web-Fonts',
            'CARD_HEALTH'   => 'Systemprüfungen',

            'COL_FILE'     => 'Datei',
            'COL_SOURCES'  => 'Quellen',
            'COL_ORIGINAL' => 'Original',
            'COL_MINIFIED' => 'Minifiziert',
            'COL_GZIP'     => 'gzip gesch.',
            'COL_SAVED'    => 'Gespart',
            'COL_BUILT'    => 'Gebaut',
            'COL_SIZE'     => 'Größe',
            'COL_CACHED'   => 'Gecacht',


            'BUNDLE_SOURCES'   => '%d Dateien',
            'SOURCE_DELETED'   => 'Quelle gelöscht',
            'CACHE_EMPTY'      => 'Der Asset-Cache ist leer — es wurde noch nichts gebaut.',
            'FONTS_EMPTY'      => 'Es werden keine Web-Fonts selbst gehostet. Templates laden Fonts mit insertWebFont().',
            'NOT_MINIFIED'     => 'nicht minifiziert',

            'CHK_ASSETS_DIR'    => 'Asset-Cache-Verzeichnis ist beschreibbar',
            'CHK_ASSETS_DIR_T'  => 'Der Webserver kann in %s Dateien anlegen und ersetzen.',
            'CHK_FONTS_DIR'     => 'Font-Cache-Verzeichnis ist beschreibbar',
            'CHK_FONTS_DIR_T'   => 'Selbst gehostete Fonts können nach %s heruntergeladen werden.',
            'CHK_MINLIB'        => 'JavaScript-Minifier',
            'CHK_MINLIB_NO'     => 'matthiasmullie/minify ist nicht installiert. Für vollständige JS-Minifizierung nach include/matthiasmullie/ legen.',
            'CHK_CURL'          => 'cURL ist verfügbar',
            'CHK_CURL_T'        => 'Nötig, um Web-Fonts über insertWebFont() selbst zu hosten.',
            'CHK_PINNED'        => '%d Konstante(n) in config.php fixiert',
            'CHK_PINNED_T'      => 'Verschiebe diese nach var/config_constants.ini.php, damit dieses Tool sie verwalten kann und ein Update sie nicht entfernt: %s.',
        ],

        'MSG' => [],
    ],

    // ═══════════════════════════════════════════════════════════════════ NL ═══
    'NL' => [
        'module_name'        => 'Asset Optimizer',
        'module_description' => 'Beheert WBCE\'s asset-pijplijn (framework/Assets/AssetQueue.php): CSS/JS-minificatie, bundeling en browser-cachebusting, plus een cache-overzicht met bytebesparing per bundle en bronlijsten, de cache voor zelf-gehoste webfonts en systeemcontroles.',
        'TXT' => [
            'TAB_SETTINGS' => 'Instellingen',
            'TAB_CACHE'    => 'Cache & status',
            'TAB_DOCS'     => 'Documentatie',
            'DOC_GUIDE'        => 'Handleiding',
            'DOC_EMBED'        => 'Assets in templates',
            'DOC_FONTS'        => 'Webfonts',
            'DOC_REFERENCE'    => 'Referentie',
            'DOC_ON_THIS_PAGE' => 'Op deze pagina',
            'DOC_SOURCE'      => 'Bron:',
            'SAVE'         => 'Instellingen opslaan',
            'ENABLED'      => 'Aan',
            'DISABLED'     => 'Uit',
            'PINNED_TITLE' => '%d constante(n) gedefinieerd in config.php',
            'LOCKED_NOTE'  => 'Gedefinieerd in config.php — hier alleen-lezen.',
            'CARD_MINIFY'   => 'Minificatie',
            'CARD_BUST'     => 'Browser-cachebusting',
            'CARD_ADVANCED' => 'Geavanceerd',
            'FOOT_INI'      => 'Wordt geschreven naar var/config_constants.ini.php — updateveilig.',
            'FOOT_DB'       => 'Wordt geschreven naar de settings-tabel — gedeeld met Outputfilter Dashboard.',
            'MINIFY_CSS_LABEL' => 'CSS minificeren',
            'MINIFY_JS_LABEL' => 'JavaScript minificeren',
            'MINIFY_USE_SUFFIX_LABEL' => '.min-achtervoegsel behouden',
            'ASSETS_MINIFY_DEBUG_LABEL' => 'Ontwikkelaars-bronweergave',
            'OPF_ASSETS_CACHE_BUSTING_LABEL' => 'Frontend',
            'OPF_ASSETS_CACHE_BUSTING_BE_LABEL' => 'Backend',
            'MINIFY_ASSETS_DIR_LABEL' => 'Cachemap',
            'MINIFY_ASSETS_DIR_PH'    => '/absoluut/pad/naar/cache/  — leeg voor de standaard',
            'ASSET_QUEUE_DEBUG_LABEL' => 'Admin-consolefouten',
            'STAT_FILES'      => 'bestanden in cache',
            'STAT_ORIGINAL'   => 'origineel',
            'STAT_OPTIMISED'  => 'geoptimaliseerd',
            'STAT_GZIP'       => 'gzip geschat',
            'STAT_SAVED'      => 'bespaard',
            'STAT_BUILT'      => 'laatste build',
            'CLEAR_ASSETS'  => 'Asset-cache leegmaken',
            'CLEAR_FONTS'   => 'Font-cache leegmaken',
            'CLEAR_ASSETS_CONFIRM' => 'Asset-cache leegmaken? Bundles en geminificeerde bestanden worden bij de volgende paginaweergave opnieuw gebouwd.',
            'CLEAR_FONTS_CONFIRM'  => 'Webfont-cache leegmaken? Fonts worden bij de volgende paginaweergave opnieuw gedownload.',
            'CARD_BUNDLES'  => 'Bundles',
            'CARD_MINFILES' => 'Geminificeerde bestanden',
            'CARD_FONTS'    => 'Zelf-gehoste webfonts',
            'CARD_HEALTH'   => 'Systeemcontroles',
            'COL_FILE'     => 'Bestand',
            'COL_SOURCES'  => 'Bronnen',
            'COL_ORIGINAL' => 'Origineel',
            'COL_MINIFIED' => 'Geminificeerd',
            'COL_GZIP'     => 'gzip gesch.',
            'COL_SAVED'    => 'Bespaard',
            'COL_BUILT'    => 'Gebouwd',
            'COL_SIZE'     => 'Grootte',
            'COL_CACHED'   => 'Gecacht',
            'BUNDLE_SOURCES'   => '%d bestanden',
            'SOURCE_DELETED'   => 'bron verwijderd',
            'CACHE_EMPTY'      => 'De asset-cache is leeg — er is nog niets gebouwd.',
            'FONTS_EMPTY'      => 'Er worden geen webfonts zelf gehost. Templates laden fonts met insertWebFont().',
            'NOT_MINIFIED'     => 'niet geminificeerd',
            'CHK_MINLIB'       => 'JavaScript-minifier',
            'CHK_CURL'         => 'cURL is beschikbaar',
        ],
        'MSG' => [],
    ],

    // ═══════════════════════════════════════════════════════════════════ PL ═══
    'PL' => [
        'module_name'        => 'Asset Optimizer',
        'module_description' => 'Zarządza potokiem zasobów WBCE (framework/Assets/AssetQueue.php): minifikacją CSS/JS, łączeniem w paczki i wymuszaniem odświeżania pamięci podręcznej przeglądarki, a także widokiem pamięci podręcznej z oszczędnością bajtów na paczkę i listami źródeł, pamięcią podręczną samodzielnie hostowanych czcionek internetowych oraz testami kondycji.',
        'TXT' => [
            'TAB_SETTINGS' => 'Ustawienia',
            'TAB_CACHE'    => 'Pamięć podręczna i status',
            'TAB_DOCS'     => 'Dokumentacja',
            'DOC_GUIDE'        => 'Przewodnik',
            'DOC_EMBED'        => 'Zasoby w szablonach',
            'DOC_FONTS'        => 'Czcionki internetowe',
            'DOC_REFERENCE'    => 'Pełna dokumentacja',
            'DOC_ON_THIS_PAGE' => 'Na tej stronie',
            'DOC_SOURCE'      => 'Źródło:',
            'SAVE'         => 'Zapisz ustawienia',
            'ENABLED'      => 'Wł.',
            'DISABLED'     => 'Wył.',
            'PINNED_TITLE' => '%d stała(-e) zdefiniowana(-e) w config.php',
            'LOCKED_NOTE'  => 'Zdefiniowana w config.php — tutaj tylko do odczytu.',
            'CARD_MINIFY'   => 'Minifikacja',
            'CARD_BUST'     => 'Wymuszanie odświeżania cache przeglądarki',
            'CARD_ADVANCED' => 'Zaawansowane',
            'FOOT_INI'      => 'Zapisywane do var/config_constants.ini.php — bezpieczne przy aktualizacji.',
            'FOOT_DB'       => 'Zapisywane do tabeli settings — współdzielone z Outputfilter Dashboard.',
            'MINIFY_CSS_LABEL' => 'Minifikuj CSS',
            'MINIFY_JS_LABEL' => 'Minifikuj JavaScript',
            'MINIFY_USE_SUFFIX_LABEL' => 'Zachowaj przyrostek .min',
            'ASSETS_MINIFY_DEBUG_LABEL' => 'Widok źródeł dla programistów',
            'OPF_ASSETS_CACHE_BUSTING_LABEL' => 'Frontend',
            'OPF_ASSETS_CACHE_BUSTING_BE_LABEL' => 'Backend',
            'MINIFY_ASSETS_DIR_LABEL' => 'Katalog pamięci podręcznej',
            'MINIFY_ASSETS_DIR_PH'    => '/bezwzględna/ścieżka/do/cache/  — puste dla domyślnej',
            'ASSET_QUEUE_DEBUG_LABEL' => 'Błędy konsoli administratora',
            'STAT_FILES'      => 'plików w pamięci podręcznej',
            'STAT_ORIGINAL'   => 'oryginał',
            'STAT_OPTIMISED'  => 'zoptymalizowane',
            'STAT_GZIP'       => 'gzip szacow.',
            'STAT_SAVED'      => 'zaoszczędzono',
            'STAT_BUILT'      => 'ostatni build',
            'CLEAR_ASSETS'  => 'Wyczyść pamięć podręczną zasobów',
            'CLEAR_FONTS'   => 'Wyczyść pamięć podręczną czcionek',
            'CLEAR_ASSETS_CONFIRM' => 'Wyczyścić pamięć podręczną zasobów? Paczki i zminifikowane pliki zostaną odbudowane przy następnym wczytaniu strony.',
            'CLEAR_FONTS_CONFIRM'  => 'Wyczyścić pamięć podręczną czcionek internetowych? Czcionki zostaną ponownie pobrane przy następnym wczytaniu strony.',
            'CARD_BUNDLES'  => 'Paczki',
            'CARD_MINFILES' => 'Zminifikowane pliki',
            'CARD_FONTS'    => 'Samodzielnie hostowane czcionki internetowe',
            'CARD_HEALTH'   => 'Testy kondycji',
            'COL_FILE'     => 'Plik',
            'COL_SOURCES'  => 'Źródła',
            'COL_ORIGINAL' => 'Oryginał',
            'COL_MINIFIED' => 'Zminifikowany',
            'COL_GZIP'     => 'gzip szac.',
            'COL_SAVED'    => 'Zaoszczędzono',
            'COL_BUILT'    => 'Zbudowano',
            'COL_SIZE'     => 'Rozmiar',
            'COL_CACHED'   => 'W pamięci podręcznej',
            'BUNDLE_SOURCES'   => '%d plików',
            'SOURCE_DELETED'   => 'źródło usunięte',
            'CACHE_EMPTY'      => 'Pamięć podręczna zasobów jest pusta — nic jeszcze nie zbudowano.',
            'FONTS_EMPTY'      => 'Żadne czcionki internetowe nie są hostowane samodzielnie. Szablony ładują czcionki przez insertWebFont().',
            'NOT_MINIFIED'     => 'niezminifikowany',
            'CHK_MINLIB'       => 'Minifikator JavaScript',
            'CHK_CURL'         => 'cURL jest dostępny',
        ],
        'MSG' => [],
    ],

    // ═══════════════════════════════════════════════════════════════════ NO ═══
    'NO' => [
        'module_name'        => 'Asset Optimizer',
        'module_description' => 'Administrerer WBCEs ressurskø (framework/Assets/AssetQueue.php): CSS/JS-minifisering, bunting og nettleser-cache-busting, samt en cache-oversikt med byte-besparelse per bunt og kildelister, mellomlageret for selvhostede web-fonter og helsesjekker.',
        'TXT' => [
            'TAB_SETTINGS' => 'Innstillinger',
            'TAB_CACHE'    => 'Cache og status',
            'TAB_DOCS'     => 'Dokumentasjon',
            'DOC_GUIDE'        => 'Veiledning',
            'DOC_EMBED'        => 'Ressurser i maler',
            'DOC_FONTS'        => 'Web-fonter',
            'DOC_REFERENCE'    => 'Full referanse',
            'DOC_ON_THIS_PAGE' => 'På denne siden',
            'DOC_SOURCE'      => 'Kilde:',
            'SAVE'         => 'Lagre innstillinger',
            'ENABLED'      => 'På',
            'DISABLED'     => 'Av',
            'PINNED_TITLE' => '%d konstant(er) definert i config.php',
            'LOCKED_NOTE'  => 'Definert i config.php — skrivebeskyttet her.',
            'CARD_MINIFY'   => 'Minifisering',
            'CARD_BUST'     => 'Nettleser-cache-busting',
            'CARD_ADVANCED' => 'Avansert',
            'FOOT_INI'      => 'Skrives til var/config_constants.ini.php — oppdateringssikkert.',
            'FOOT_DB'       => 'Skrives til settings-tabellen — deles med Outputfilter Dashboard.',
            'MINIFY_CSS_LABEL' => 'Minifiser CSS',
            'MINIFY_JS_LABEL' => 'Minifiser JavaScript',
            'MINIFY_USE_SUFFIX_LABEL' => 'Behold .min-suffikset',
            'ASSETS_MINIFY_DEBUG_LABEL' => 'Kildevisning for utviklere',
            'OPF_ASSETS_CACHE_BUSTING_LABEL' => 'Frontend',
            'OPF_ASSETS_CACHE_BUSTING_BE_LABEL' => 'Backend',
            'MINIFY_ASSETS_DIR_LABEL' => 'Cache-mappe',
            'MINIFY_ASSETS_DIR_PH'    => '/absolutt/sti/til/cache/  — tom for standard',
            'ASSET_QUEUE_DEBUG_LABEL' => 'Admin-konsollfeil',
            'STAT_FILES'      => 'cachede filer',
            'STAT_ORIGINAL'   => 'original',
            'STAT_OPTIMISED'  => 'optimalisert',
            'STAT_GZIP'       => 'gzip anslått',
            'STAT_SAVED'      => 'spart',
            'STAT_BUILT'      => 'siste bygg',
            'CLEAR_ASSETS'  => 'Tøm ressurs-cache',
            'CLEAR_FONTS'   => 'Tøm font-cache',
            'CLEAR_ASSETS_CONFIRM' => 'Tømme ressurs-cachen? Bunter og minifiserte filer bygges på nytt ved neste sidevisning.',
            'CLEAR_FONTS_CONFIRM'  => 'Tømme web-font-cachen? Fontene lastes ned på nytt ved neste sidevisning.',
            'CARD_BUNDLES'  => 'Bunter',
            'CARD_MINFILES' => 'Minifiserte filer',
            'CARD_FONTS'    => 'Selvhostede web-fonter',
            'CARD_HEALTH'   => 'Helsesjekker',
            'COL_FILE'     => 'Fil',
            'COL_SOURCES'  => 'Kilder',
            'COL_ORIGINAL' => 'Original',
            'COL_MINIFIED' => 'Minifisert',
            'COL_GZIP'     => 'gzip anslått',
            'COL_SAVED'    => 'Spart',
            'COL_BUILT'    => 'Bygget',
            'COL_SIZE'     => 'Størrelse',
            'COL_CACHED'   => 'Cachet',
            'BUNDLE_SOURCES'   => '%d filer',
            'SOURCE_DELETED'   => 'kilde slettet',
            'CACHE_EMPTY'      => 'Ressurs-cachen er tom — ingenting er bygget ennå.',
            'FONTS_EMPTY'      => 'Ingen web-fonter hostes selv. Maler laster fonter med insertWebFont().',
            'NOT_MINIFIED'     => 'ikke minifisert',
            'CHK_MINLIB'       => 'JavaScript-minifier',
            'CHK_CURL'         => 'cURL er tilgjengelig',
        ],
        'MSG' => [],
    ],

    // ═══════════════════════════════════════════════════════════════════ FR ═══
    'FR' => [
        'module_name'        => 'Asset Optimizer',
        'module_description' => 'Gère le pipeline d\'assets de WBCE (framework/Assets/AssetQueue.php) : minification CSS/JS, regroupement et cache-busting navigateur, ainsi qu\'une vue du cache avec l\'économie d\'octets par bundle et les listes de sources, le cache des polices web auto-hébergées et des contrôles de santé.',
        'TXT' => [
            'TAB_SETTINGS' => 'Réglages',
            'TAB_CACHE'    => 'Cache et état',
            'TAB_DOCS'     => 'Documentation',
            'DOC_GUIDE'        => 'Guide',
            'DOC_EMBED'        => 'Assets dans les templates',
            'DOC_FONTS'        => 'Polices web',
            'DOC_REFERENCE'    => 'Référence complète',
            'DOC_ON_THIS_PAGE' => 'Sur cette page',
            'DOC_SOURCE'      => 'Source :',
            'SAVE'         => 'Enregistrer les réglages',
            'ENABLED'      => 'Activé',
            'DISABLED'     => 'Désactivé',
            'PINNED_TITLE' => '%d constante(s) définie(s) dans config.php',
            'LOCKED_NOTE'  => 'Définie dans config.php — lecture seule ici.',
            'CARD_MINIFY'   => 'Minification',
            'CARD_BUST'     => 'Cache-busting navigateur',
            'CARD_ADVANCED' => 'Avancé',
            'FOOT_INI'      => 'Écrit dans var/config_constants.ini.php — préservé lors des mises à jour.',
            'FOOT_DB'       => 'Écrit dans la table settings — partagé avec Outputfilter Dashboard.',
            'MINIFY_CSS_LABEL' => 'Minifier le CSS',
            'MINIFY_JS_LABEL' => 'Minifier le JavaScript',
            'MINIFY_USE_SUFFIX_LABEL' => 'Conserver le suffixe .min',
            'ASSETS_MINIFY_DEBUG_LABEL' => 'Vue source développeur',
            'OPF_ASSETS_CACHE_BUSTING_LABEL' => 'Front-end',
            'OPF_ASSETS_CACHE_BUSTING_BE_LABEL' => 'Back-end',
            'MINIFY_ASSETS_DIR_LABEL' => 'Répertoire du cache',
            'MINIFY_ASSETS_DIR_PH'    => '/chemin/absolu/vers/cache/  — vide pour la valeur par défaut',
            'ASSET_QUEUE_DEBUG_LABEL' => 'Erreurs console admin',
            'STAT_FILES'      => 'fichiers en cache',
            'STAT_ORIGINAL'   => 'original',
            'STAT_OPTIMISED'  => 'optimisé',
            'STAT_GZIP'       => 'gzip est.',
            'STAT_SAVED'      => 'économisé',
            'STAT_BUILT'      => 'dernier build',
            'CLEAR_ASSETS'  => 'Vider le cache des assets',
            'CLEAR_FONTS'   => 'Vider le cache des polices',
            'CLEAR_ASSETS_CONFIRM' => 'Vider le cache des assets ? Les bundles et fichiers minifiés seront reconstruits au prochain chargement de page.',
            'CLEAR_FONTS_CONFIRM'  => 'Vider le cache des polices web ? Les polices seront re-téléchargées au prochain chargement de page.',
            'CARD_BUNDLES'  => 'Bundles',
            'CARD_MINFILES' => 'Fichiers minifiés',
            'CARD_FONTS'    => 'Polices web auto-hébergées',
            'CARD_HEALTH'   => 'Contrôles de santé',
            'COL_FILE'     => 'Fichier',
            'COL_SOURCES'  => 'Sources',
            'COL_ORIGINAL' => 'Original',
            'COL_MINIFIED' => 'Minifié',
            'COL_GZIP'     => 'gzip est.',
            'COL_SAVED'    => 'Économisé',
            'COL_BUILT'    => 'Construit',
            'COL_SIZE'     => 'Taille',
            'COL_CACHED'   => 'En cache',
            'BUNDLE_SOURCES'   => '%d fichiers',
            'SOURCE_DELETED'   => 'source supprimée',
            'CACHE_EMPTY'      => 'Le cache des assets est vide — rien n\'a encore été construit.',
            'FONTS_EMPTY'      => 'Aucune police web n\'est auto-hébergée. Les templates chargent les polices avec insertWebFont().',
            'NOT_MINIFIED'     => 'non minifié',
            'CHK_MINLIB'       => 'Minifieur JavaScript',
            'CHK_CURL'         => 'cURL est disponible',
        ],
        'MSG' => [],
    ],

    // ═══════════════════════════════════════════════════════════════════ IT ═══
    'IT' => [
        'module_name'        => 'Asset Optimizer',
        'module_description' => 'Gestisce la pipeline degli asset di WBCE (framework/Assets/AssetQueue.php): minificazione CSS/JS, raggruppamento e cache-busting del browser, oltre a una vista della cache con il risparmio di byte per bundle e gli elenchi delle sorgenti, la cache dei web font self-hosted e i controlli di integrità.',
        'TXT' => [
            'TAB_SETTINGS' => 'Impostazioni',
            'TAB_CACHE'    => 'Cache e stato',
            'TAB_DOCS'     => 'Documentazione',
            'DOC_GUIDE'        => 'Guida',
            'DOC_EMBED'        => 'Asset nei template',
            'DOC_FONTS'        => 'Web font',
            'DOC_REFERENCE'    => 'Riferimento completo',
            'DOC_ON_THIS_PAGE' => 'In questa pagina',
            'DOC_SOURCE'      => 'Sorgente:',
            'SAVE'         => 'Salva le impostazioni',
            'ENABLED'      => 'Attivo',
            'DISABLED'     => 'Disattivo',
            'PINNED_TITLE' => '%d costante/i definita/e in config.php',
            'LOCKED_NOTE'  => 'Definita in config.php — di sola lettura qui.',
            'CARD_MINIFY'   => 'Minificazione',
            'CARD_BUST'     => 'Cache-busting del browser',
            'CARD_ADVANCED' => 'Avanzate',
            'FOOT_INI'      => 'Scritto in var/config_constants.ini.php — sicuro agli aggiornamenti.',
            'FOOT_DB'       => 'Scritto nella tabella settings — condiviso con Outputfilter Dashboard.',
            'MINIFY_CSS_LABEL' => 'Minifica CSS',
            'MINIFY_JS_LABEL' => 'Minifica JavaScript',
            'MINIFY_USE_SUFFIX_LABEL' => 'Mantieni il suffisso .min',
            'ASSETS_MINIFY_DEBUG_LABEL' => 'Vista sorgente per sviluppatori',
            'OPF_ASSETS_CACHE_BUSTING_LABEL' => 'Front-end',
            'OPF_ASSETS_CACHE_BUSTING_BE_LABEL' => 'Back-end',
            'MINIFY_ASSETS_DIR_LABEL' => 'Directory della cache',
            'MINIFY_ASSETS_DIR_PH'    => '/percorso/assoluto/alla/cache/  — vuoto per il valore predefinito',
            'ASSET_QUEUE_DEBUG_LABEL' => 'Errori console admin',
            'STAT_FILES'      => 'file in cache',
            'STAT_ORIGINAL'   => 'originale',
            'STAT_OPTIMISED'  => 'ottimizzato',
            'STAT_GZIP'       => 'gzip stim.',
            'STAT_SAVED'      => 'risparmiato',
            'STAT_BUILT'      => 'ultima build',
            'CLEAR_ASSETS'  => 'Svuota la cache degli asset',
            'CLEAR_FONTS'   => 'Svuota la cache dei font',
            'CLEAR_ASSETS_CONFIRM' => 'Svuotare la cache degli asset? I bundle e i file minificati verranno ricostruiti al prossimo caricamento di pagina.',
            'CLEAR_FONTS_CONFIRM'  => 'Svuotare la cache dei web font? I font verranno riscaricati al prossimo caricamento di pagina.',
            'CARD_BUNDLES'  => 'Bundle',
            'CARD_MINFILES' => 'File minificati',
            'CARD_FONTS'    => 'Web font self-hosted',
            'CARD_HEALTH'   => 'Controlli di integrità',
            'COL_FILE'     => 'File',
            'COL_SOURCES'  => 'Sorgenti',
            'COL_ORIGINAL' => 'Originale',
            'COL_MINIFIED' => 'Minificato',
            'COL_GZIP'     => 'gzip stim.',
            'COL_SAVED'    => 'Risparmiato',
            'COL_BUILT'    => 'Compilato',
            'COL_SIZE'     => 'Dimensione',
            'COL_CACHED'   => 'In cache',
            'BUNDLE_SOURCES'   => '%d file',
            'SOURCE_DELETED'   => 'sorgente eliminata',
            'CACHE_EMPTY'      => 'La cache degli asset è vuota — non è stato ancora costruito nulla.',
            'FONTS_EMPTY'      => 'Nessun web font è self-hosted. I template caricano i font con insertWebFont().',
            'NOT_MINIFIED'     => 'non minificato',
            'CHK_MINLIB'       => 'Minificatore JavaScript',
            'CHK_CURL'         => 'cURL è disponibile',
        ],
        'MSG' => [],
    ],

    // ═══════════════════════════════════════════════════════════════════ ES ═══
    'ES' => [
        'module_name'        => 'Asset Optimizer',
        'module_description' => 'Gestiona la canalización de recursos de WBCE (framework/Assets/AssetQueue.php): minificación de CSS/JS, agrupación y cache-busting del navegador, además de una vista de la caché con el ahorro de bytes por paquete y las listas de orígenes, la caché de fuentes web autoalojadas y comprobaciones de estado.',
        'TXT' => [
            'TAB_SETTINGS' => 'Ajustes',
            'TAB_CACHE'    => 'Caché y estado',
            'TAB_DOCS'     => 'Documentación',
            'DOC_GUIDE'        => 'Guía',
            'DOC_EMBED'        => 'Recursos en plantillas',
            'DOC_FONTS'        => 'Fuentes web',
            'DOC_REFERENCE'    => 'Referencia completa',
            'DOC_ON_THIS_PAGE' => 'En esta página',
            'DOC_SOURCE'      => 'Origen:',
            'SAVE'         => 'Guardar ajustes',
            'ENABLED'      => 'Activado',
            'DISABLED'     => 'Desactivado',
            'PINNED_TITLE' => '%d constante(s) definida(s) en config.php',
            'LOCKED_NOTE'  => 'Definida en config.php — solo lectura aquí.',
            'CARD_MINIFY'   => 'Minificación',
            'CARD_BUST'     => 'Cache-busting del navegador',
            'CARD_ADVANCED' => 'Avanzado',
            'FOOT_INI'      => 'Se escribe en var/config_constants.ini.php — a prueba de actualizaciones.',
            'FOOT_DB'       => 'Se escribe en la tabla settings — compartido con Outputfilter Dashboard.',
            'MINIFY_CSS_LABEL' => 'Minificar CSS',
            'MINIFY_JS_LABEL' => 'Minificar JavaScript',
            'MINIFY_USE_SUFFIX_LABEL' => 'Mantener el sufijo .min',
            'ASSETS_MINIFY_DEBUG_LABEL' => 'Vista de origen para desarrolladores',
            'OPF_ASSETS_CACHE_BUSTING_LABEL' => 'Front-end',
            'OPF_ASSETS_CACHE_BUSTING_BE_LABEL' => 'Back-end',
            'MINIFY_ASSETS_DIR_LABEL' => 'Directorio de caché',
            'MINIFY_ASSETS_DIR_PH'    => '/ruta/absoluta/a/cache/  — vacío para el valor predeterminado',
            'ASSET_QUEUE_DEBUG_LABEL' => 'Errores de consola de admin',
            'STAT_FILES'      => 'archivos en caché',
            'STAT_ORIGINAL'   => 'original',
            'STAT_OPTIMISED'  => 'optimizado',
            'STAT_GZIP'       => 'gzip aprox.',
            'STAT_SAVED'      => 'ahorrado',
            'STAT_BUILT'      => 'última compilación',
            'CLEAR_ASSETS'  => 'Vaciar la caché de recursos',
            'CLEAR_FONTS'   => 'Vaciar la caché de fuentes',
            'CLEAR_ASSETS_CONFIRM' => '¿Vaciar la caché de recursos? Los paquetes y archivos minificados se reconstruirán en la próxima carga de página.',
            'CLEAR_FONTS_CONFIRM'  => '¿Vaciar la caché de fuentes web? Las fuentes se volverán a descargar en la próxima carga de página.',
            'CARD_BUNDLES'  => 'Paquetes',
            'CARD_MINFILES' => 'Archivos minificados',
            'CARD_FONTS'    => 'Fuentes web autoalojadas',
            'CARD_HEALTH'   => 'Comprobaciones de estado',
            'COL_FILE'     => 'Archivo',
            'COL_SOURCES'  => 'Orígenes',
            'COL_ORIGINAL' => 'Original',
            'COL_MINIFIED' => 'Minificado',
            'COL_GZIP'     => 'gzip aprox.',
            'COL_SAVED'    => 'Ahorrado',
            'COL_BUILT'    => 'Compilado',
            'COL_SIZE'     => 'Tamaño',
            'COL_CACHED'   => 'En caché',
            'BUNDLE_SOURCES'   => '%d archivos',
            'SOURCE_DELETED'   => 'origen eliminado',
            'CACHE_EMPTY'      => 'La caché de recursos está vacía — todavía no se ha construido nada.',
            'FONTS_EMPTY'      => 'No hay fuentes web autoalojadas. Las plantillas cargan fuentes con insertWebFont().',
            'NOT_MINIFIED'     => 'sin minificar',
            'CHK_MINLIB'       => 'Minificador de JavaScript',
            'CHK_CURL'         => 'cURL está disponible',
        ],
        'MSG' => [],
    ],

    // ═══════════════════════════════════════════════════════════════════ RU ═══
    'RU' => [
        'module_name'        => 'Asset Optimizer',
        'module_description' => 'Управляет конвейером ресурсов WBCE (framework/Assets/AssetQueue.php): минификация CSS/JS, объединение и сброс кэша браузера, а также обзор кэша с экономией байтов по каждому бандлу и списками исходников, кэш самостоятельно размещённых веб-шрифтов и проверки состояния.',
        'TXT' => [
            'TAB_SETTINGS' => 'Настройки',
            'TAB_CACHE'    => 'Кэш и состояние',
            'TAB_DOCS'     => 'Документация',
            'DOC_GUIDE'        => 'Руководство',
            'DOC_EMBED'        => 'Ресурсы в шаблонах',
            'DOC_FONTS'        => 'Веб-шрифты',
            'DOC_REFERENCE'    => 'Полный справочник',
            'DOC_ON_THIS_PAGE' => 'На этой странице',
            'DOC_SOURCE'      => 'Источник:',
            'SAVE'         => 'Сохранить настройки',
            'ENABLED'      => 'Вкл.',
            'DISABLED'     => 'Выкл.',
            'PINNED_TITLE' => 'Констант в config.php: %d',
            'LOCKED_NOTE'  => 'Определена в config.php — здесь только для чтения.',
            'CARD_MINIFY'   => 'Минификация',
            'CARD_BUST'     => 'Сброс кэша браузера',
            'CARD_ADVANCED' => 'Дополнительно',
            'FOOT_INI'      => 'Записывается в var/config_constants.ini.php — не теряется при обновлении.',
            'FOOT_DB'       => 'Записывается в таблицу settings — совместно с Outputfilter Dashboard.',
            'MINIFY_CSS_LABEL' => 'Минифицировать CSS',
            'MINIFY_JS_LABEL' => 'Минифицировать JavaScript',
            'MINIFY_USE_SUFFIX_LABEL' => 'Сохранять суффикс .min',
            'ASSETS_MINIFY_DEBUG_LABEL' => 'Просмотр исходников для разработчика',
            'OPF_ASSETS_CACHE_BUSTING_LABEL' => 'Фронтенд',
            'OPF_ASSETS_CACHE_BUSTING_BE_LABEL' => 'Бэкенд',
            'MINIFY_ASSETS_DIR_LABEL' => 'Каталог кэша',
            'MINIFY_ASSETS_DIR_PH'    => '/абсолютный/путь/к/cache/  — пусто для значения по умолчанию',
            'ASSET_QUEUE_DEBUG_LABEL' => 'Ошибки консоли администратора',
            'STAT_FILES'      => 'файлов в кэше',
            'STAT_ORIGINAL'   => 'оригинал',
            'STAT_OPTIMISED'  => 'оптимизировано',
            'STAT_GZIP'       => 'gzip оценка',
            'STAT_SAVED'      => 'сэкономлено',
            'STAT_BUILT'      => 'последняя сборка',
            'CLEAR_ASSETS'  => 'Очистить кэш ресурсов',
            'CLEAR_FONTS'   => 'Очистить кэш шрифтов',
            'CLEAR_ASSETS_CONFIRM' => 'Очистить кэш ресурсов? Бандлы и минифицированные файлы будут пересобраны при следующей загрузке страницы.',
            'CLEAR_FONTS_CONFIRM'  => 'Очистить кэш веб-шрифтов? Шрифты будут загружены заново при следующей загрузке страницы.',
            'CARD_BUNDLES'  => 'Бандлы',
            'CARD_MINFILES' => 'Минифицированные файлы',
            'CARD_FONTS'    => 'Самостоятельно размещённые веб-шрифты',
            'CARD_HEALTH'   => 'Проверки состояния',
            'COL_FILE'     => 'Файл',
            'COL_SOURCES'  => 'Исходники',
            'COL_ORIGINAL' => 'Оригинал',
            'COL_MINIFIED' => 'Минифицировано',
            'COL_GZIP'     => 'gzip оц.',
            'COL_SAVED'    => 'Экономия',
            'COL_BUILT'    => 'Собрано',
            'COL_SIZE'     => 'Размер',
            'COL_CACHED'   => 'В кэше',
            'BUNDLE_SOURCES'   => 'файлов: %d',
            'SOURCE_DELETED'   => 'исходник удалён',
            'CACHE_EMPTY'      => 'Кэш ресурсов пуст — ещё ничего не собрано.',
            'FONTS_EMPTY'      => 'Веб-шрифты не размещаются самостоятельно. Шаблоны загружают шрифты через insertWebFont().',
            'NOT_MINIFIED'     => 'без минификации',
            'CHK_MINLIB'       => 'Минификатор JavaScript',
            'CHK_CURL'         => 'cURL доступен',
        ],
        'MSG' => [],
    ],
];
