<?php
/**
 * tinymce_wbce — generate_theme.php
 * Generates theme-wbce.min.css from saved color settings.
 * Called from tool.php after saving Tab 3 settings.
 * @author  Slugger & Claude KI
 * @license GNU GPL2
 */

if (!defined('WB_PATH')) { return; }

require_once WB_PATH . '/framework/Settings.php';

function tinymce_wbce_generate_theme(array $cfg = []): bool
{
    // Defaults
    $defaults = [
        'wbce_toolbar'  => '#3c4150',
        'wbce_toolbar2' => '#2d3139',
        'wbce_accent'   => '#5683b2',
        'wbce_navbar'   => '#e8eaee',
        'wbce_status'   => '#46505f',
    ];

    // If no cfg passed, read from DB
    if (empty($cfg)) {
        $stored = json_decode(Settings::get('tinymce_cfg', '{}'), true) ?? [];
        $cfg = array_merge($defaults, $stored);
    } else {
        $cfg = array_merge($defaults, $cfg);
    }

    $toolbar  = $cfg['wbce_toolbar']    ?? '#3c4150';
    $toolbar2 = $cfg['wbce_toolbar2']   ?? '#2d3139';
    $accent   = $cfg['wbce_accent']     ?? '#5683b2';
    $navbar   = $cfg['wbce_navbar']     ?? '#e8eaee';
    $status   = $cfg['wbce_status']     ?? '#46505f';
    $iconClr  = $cfg['wbce_icon_color'] ?? '#dddddd';
    $iconHov  = $cfg['wbce_icon_hover'] ?? '#ffffff';

    // Validate hex colors
    foreach ([$toolbar, $toolbar2, $accent, $navbar, $status, $iconClr, $iconHov] as &$c) {
        if (!preg_match('/^#[0-9a-fA-F]{3,6}$/', $c)) {
            $c = '#46505f'; // fallback
        }
    }
    unset($c);

    // Derive hover/active variants (slightly darker)
    $accentDark  = _tmce_darken($accent, 15);
    $navbarHover = $accent;

    // Base: Material theme from elfinder (contains the icon font, overrides toolbar.png)
    // Our color overrides go on top (without !important where possible)
    $matPath = WB_PATH . '/modules/elfinder/ef/themes/material/css/theme-gray.min.css';
    $matBase = file_exists($matPath) ? file_get_contents($matPath) : '';

    // Fix all relative paths → absolute URLs
    $iconBase = WB_URL . '/modules/elfinder/ef/themes/material/icons/';
    $imgBase  = WB_URL . '/modules/elfinder/ef/img/';
    $sprBase  = WB_URL . '/modules/elfinder/ef/img/';

    // Font paths (various relative notations)
    $matBase = str_replace(
        ['url(../icons/', 'url(../font/', "url('../font/", 'url("../font/'],
        ['url(' . $iconBase, 'url(' . $iconBase, "url('" . $iconBase, 'url("' . $iconBase],
        $matBase
    );

    // img paths (sprites etc.)
    $matBase = str_replace('url(../img/', 'url(' . $imgBase, $matBase);
    $matBase = str_replace('url("../img/', 'url("' . $imgBase, $matBase);
    $matBase = preg_replace('/url\(\.\.\/img\//', 'url(' . $imgBase, $matBase);
    $matBase = preg_replace('/url\("\.\.\/img\//', 'url("' . $imgBase, $matBase);

    $css = <<<CSS
/* === theme-wbce — Generated by tinymce_wbce === */
/* Base: Material Theme (Icon-Font) | Colors: Toolbar={$toolbar} Accent={$accent} */

{$matBase}

/* === WBCE Color Overrides === */

/* Toolbar background */
.elfinder-toolbar { background: {$toolbar} !important; border-bottom: 2px solid {$toolbar2} !important; }

/* Toolbar icon color (Material icon font) */
.elfinder-toolbar .elfinder-button-icon { color: {$iconClr} !important; }
.elfinder-toolbar .elfinder-button:hover .elfinder-button-icon,
.elfinder-toolbar .elfinder-button.ui-state-hover .elfinder-button-icon,
.elfinder-toolbar .elfinder-button.ui-state-active .elfinder-button-icon { color: {$iconHov} !important; }

/* Navbar */
.elfinder .elfinder-navbar { background: {$navbar} !important; }
.elfinder-navbar-dir.ui-state-hover,
.elfinder-navbar-dir.ui-state-active { background: {$accent} !important; background-image: none !important; color: #fff !important; }

/* File selection */
.elfinder-cwd-file.ui-state-hover,
.elfinder-cwd-file.ui-selected.ui-state-hover { background: {$accent} !important; background-image: none !important; }
.elfinder-cwd-file.ui-selected { background: {$accentDark} !important; background-image: none !important; }

/* Status bar */
.elfinder .elfinder-statusbar { background: {$status} !important; }

/* Dialog title bar */
.elfinder-dialog .ui-dialog-titlebar,
.elfinder-quicklook .ui-dialog-titlebar { background: {$toolbar} !important; background-image: none !important; color: #fff !important; border: 0 !important; }

/* Context menu */
.elfinder .elfinder-contextmenu-item.ui-state-hover,
.elfinder .elfinder-contextmenu-item.ui-state-active { background: {$accent} !important; background-image: none !important; }

/* No double folder icon */
.elfinder-cwd-icon.elfinder-cwd-icon-directory:after { content: none !important; display: none !important; }

/* Filename hover fix — jQuery UI sets color inline, hence the JS override */
CSS;

    // JS inline-style override after elfinder init
    $css .= <<<CSS

/* Filename hover — all possible selectors */
.elfinder-cwd-file .elfinder-cwd-filename.ui-state-hover,
.elfinder-cwd-view-icons .elfinder-cwd-file .ui-state-active,
.elfinder-cwd-view-icons .elfinder-cwd-file .ui-state-hover,
.elfinder-disabled .elfinder-cwd table td.ui-state-hover,
.elfinder-disabled .elfinder-cwd-view-icons .elfinder-cwd-file .elfinder-cwd-filename.ui-state-hover { color: #fff !important; }
CSS;

    $outPath = WB_PATH . '/modules/tinymce_wbce/css/elfinder-material/css/theme-wbce.min.css';

    // Check write permission
    if (!is_writable($outPath) && !is_writable(dirname($outPath))) {
        error_log('tinymce_wbce: Cannot write theme-wbce.min.css — check file permissions: ' . $outPath);
        return false;
    }

    $result = file_put_contents($outPath, $css);
    if ($result === false) {
        error_log('tinymce_wbce: file_put_contents failed for ' . $outPath);
        return false;
    }
    return true;
}

/**
 * Darken a hex color by $amount (0-255)
 */
function _tmce_darken(string $hex, int $amount): string
{
    $hex = ltrim($hex, '#');
    if (strlen($hex) === 3) {
        $hex = $hex[0].$hex[0].$hex[1].$hex[1].$hex[2].$hex[2];
    }
    $r = max(0, hexdec(substr($hex, 0, 2)) - $amount);
    $g = max(0, hexdec(substr($hex, 2, 2)) - $amount);
    $b = max(0, hexdec(substr($hex, 4, 2)) - $amount);
    return sprintf('#%02x%02x%02x', $r, $g, $b);
}
