editAreaLoader.lang["no"]={
new_document: "nytt tomt dokument",
search_button: "s&oslash;k og erstatt",
search_command: "s&oslash;k etter neste/ &aring;pne s&oslash;ke omr&aring;det",
search: "s&oslash;k",
replace: "erstatt",
replace_command: "erstatt / aring;pne s&oslash;ke omr&aring;det",
find_next: "finn neste",
replace_all: "erstatt alle",
reg_exp: "standard uttrykk",
match_case: "skill mellom store/ sm&aring; bokstaver",
not_found: "ikke funnetnot found.",
occurrence_replaced: "alle forekomstene ble endret.",
search_field_empty: "Tomt s&oslash;kefelt",
restart_search_at_begin: "Du er kommet til slutten av s&oslash;keomr&aring;ede. Vil du starte fra begynnelsen.",
move_popup: "flytt s&oslash;ke vinuet",
font_size: "--Skrift s&oslash;rrelse--",
go_to_line: "g&aring; til linje",
go_to_line_prompt: "g&aring; til linje nummer:",
undo: "angre",
redo: "gj&oslash;re igjen",
change_smooth_selection: "aktivere/ deaktivere visnings alternativer(gj&oslash;r skjermvisningen smartere, men gir h&oslash;yere prosessor belastning)",
highlight: "skru merking av s&oslash;keord av/ p&aring;",
reset_highlight: "starte markeringen p&aring; nytt(hvis den er usynkron med deksten)",
help: "om",
save: "lagre",
load: "laste",
line_abbr: "Ln",
char_abbr: "Ch",
position: "Posisjon",
total: "Total",
close_popup: "lukk vindu",
shortcuts: "Snarveier",
add_tab: "legg til tabulering i teksten",
remove_tab: "fj&aelig;rn tabulering i teksten",
about_notice: "OBS!: markering av s&oslash;ketekst er kun for tekst med sm&aring; bokstaver",
toggle: "skru redigeringsverkt&oslash;yet av/ p&aring;",
accesskey: "Tillgangsn&oslash;kkel",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Behandler...",
fullscreen: "full skjerm",
syntax_selection: "--Språk--",
syntax_css: "CSS",
syntax_html: "HTML",
syntax_js: "Javascript",
syntax_php: "Php",
syntax_python: "Python",
syntax_vb: "Visual Basic",
syntax_xml: "Xml",
syntax_c: "C",
syntax_cpp: "CPP",
syntax_basic: "Basic",
syntax_pas: "Pascal",
syntax_brainfuck: "Brainfuck",
syntax_sql: "SQL",
syntax_ruby: "Ruby",
syntax_robotstxt: "Robots txt",
syntax_tsql: "T-SQL",
syntax_perl: "Perl",
syntax_coldfusion: "Coldfusion",
close_tab: "Lukk filen"
};
